version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    # rust shouldn't be needed as we disable building the extension
    # in the readthedocs configuration

python:
  install:
    - requirements: requirements/docs.txt
    - method: pip
      path: .
