# Maintainer's notes:
# - This describes the public API of the module. It's needed because the Rust extension
#   can't expose a typed Python API directly.
# - This file is *not* autogenerated, but fortunately it doesn't change often.
#   It needs to be manually crafted because automatic generation from the implementation
#   doesn't yield the desired results.
# - Aliases are used sparingly, since they obscure the signature in some popular IDEs.
#   You'll notice lots of repetition in string literals, for example.
import enum
from abc import ABC
from collections.abc import Iterator, Mapping
from datetime import (
    date as _date,
    datetime as _datetime,
    time as _time,
    timedelta as _timedelta,
)
from os import PathLike
from typing import (
    ClassVar,
    ContextManager,
    Iterable,
    Literal,
    Sequence,
    TypeAlias,
    final,
    overload,
    type_check_only,
)

from typing_extensions import Self, deprecated, override, sentinel

__all__ = [
    # Date and time
    "Date",
    "YearMonth",
    "MonthDay",
    "IsoWeekDate",
    "Time",
    "Instant",
    "OffsetDateTime",
    "ZonedDateTime",
    "PlainDateTime",
    # Deltas and time units
    "TimeDelta",
    "ItemizedDelta",
    "ItemizedDateDelta",
    "hours",
    "minutes",
    "seconds",
    "milliseconds",
    "microseconds",
    "nanoseconds",
    # Exceptions/warnings
    "DaysAssumed24HoursWarning",
    "StaleOffsetWarning",
    "NaiveArithmeticWarning",
    "CalendarUnitCompositionWarning",
    "WheneverWarning",
    "PotentialDstBugWarning",
    "PickleOffsetMismatchWarning",
    "WheneverDeprecationWarning",
    "ImplicitDisambiguationWarning",
    "SkippedTime",
    "RepeatedTime",
    "InvalidOffsetError",
    "TimeZoneNotFoundError",
    # Enums/constants
    "Weekday",
    "MONDAY",
    "TUESDAY",
    "WEDNESDAY",
    "THURSDAY",
    "FRIDAY",
    "SATURDAY",
    "SUNDAY",
    "SYSTEM_TZ",
    # Other
    "reset_system_tz",
    "patch_current_time",
    "TimePatch",
    "get_tzpath",
    "reset_tzpath",
    "clear_tzcache",
    "available_timezones",
    "AnyDelta",
]

_EXTENSION_LOADED: bool
__version__: str

# We expose these, but we don't use them in this file. This is because
# in some popular IDEs, using aliases for literal types causes the signature to be displayed as the alias name,
# which isn't very helpful. So we just repeat the literal types everywhere instead of using the aliases.
DateDeltaUnitStr: TypeAlias = Literal[
    "years",
    "months",
    "weeks",
    "days",
]
DeltaUnitStr: TypeAlias = Literal[
    "years",
    "months",
    "weeks",
    "days",
    "hours",
    "minutes",
    "seconds",
    "nanoseconds",
]
DeltaTotalUnitStr: TypeAlias = Literal[
    "years",
    "months",
    "weeks",
    "days",
    "hours",
    "minutes",
    "seconds",
    "milliseconds",
    "microseconds",
    "nanoseconds",
]
DisambiguateStr: TypeAlias = Literal[
    "compatible",
    "later",
    "earlier",
    "raise",
]
DisambiguationStr: TypeAlias = Literal[
    "compatible",
    "later",
    "earlier",
    "raise",
]
ExactDeltaUnitStr: TypeAlias = Literal[
    "weeks",
    "days",
    "hours",
    "minutes",
    "seconds",
    "nanoseconds",
]
RoundModeStr: TypeAlias = Literal[
    "ceil",
    "expand",
    "floor",
    "trunc",
    "half_ceil",
    "half_expand",
    "half_floor",
    "half_trunc",
    "half_even",
]

OffsetMismatchStr: TypeAlias = Literal["raise", "keep_instant", "keep_local"]
TimestampUnitStr: TypeAlias = Literal[
    "second", "millisecond", "microsecond", "nanosecond"
]

# Mypy doesn't yet support using a PEP 661 sentinel value as a type.
SYSTEM_TZ = sentinel("SYSTEM_TZ")

@type_check_only
class _ISOMixin:
    @classmethod
    def parse_iso(cls, s: str, /) -> Self: ...
    def format_iso(self) -> str: ...

@type_check_only
class _OrderMixin:
    MIN: ClassVar[Self]
    MAX: ClassVar[Self]
    def __lt__(self, other: Self, /) -> bool: ...
    def __le__(self, other: Self, /) -> bool: ...
    def __gt__(self, other: Self, /) -> bool: ...
    def __ge__(self, other: Self, /) -> bool: ...

@type_check_only
class _DateOrTimeMixin(_ISOMixin, _OrderMixin):
    pass

@final
class Date(_DateOrTimeMixin):
    @overload
    def __init__(self, year: int, month: int, day: int) -> None: ...
    @overload
    def __init__(self, iso_string: str, /) -> None: ...
    @overload
    def __init__(self, py_date: _date, /) -> None: ...
    @staticmethod
    @deprecated("use Date.today(SYSTEM_TZ) instead")
    def today_in_system_tz() -> Date: ...
    @classmethod
    def today(cls, tz: str | SYSTEM_TZ, /) -> Self: ...  # type: ignore[valid-type]
    @property
    def year(self) -> int: ...
    @property
    def month(self) -> int: ...
    @property
    def day(self) -> int: ...
    def year_month(self) -> YearMonth: ...
    def month_day(self) -> MonthDay: ...
    def day_of_week(self) -> Weekday: ...
    def iso_week_date(self) -> IsoWeekDate: ...
    def day_of_year(self) -> int: ...
    def days_in_month(self) -> int: ...
    def days_in_year(self) -> int: ...
    def in_leap_year(self) -> bool: ...
    def next_day(self) -> Date: ...
    def prev_day(self) -> Date: ...
    def nth_weekday_of_month(self, n: int, weekday: Weekday, /) -> Date: ...
    def nth_weekday(self, n: int, weekday: Weekday, /) -> Date: ...
    def start_of(
        self,
        unit: Literal[
            "year",
            "month",
            "week_mon",
            "week_sun",
        ],
        /,
    ) -> Date: ...
    def end_of(
        self,
        unit: Literal[
            "year",
            "month",
            "week_mon",
            "week_sun",
        ],
        /,
    ) -> Date: ...
    def at(self, t: Time, /) -> PlainDateTime: ...
    def to_stdlib(self) -> _date: ...
    def format_iso(self, *, basic: bool = False) -> str: ...
    def format(self, pattern: str, /) -> str: ...
    def __format__(self, spec: str, /) -> str: ...
    @overload
    @classmethod
    def parse(cls, s: str, /, *, pattern: str) -> Date: ...
    @overload
    @classmethod
    @deprecated("use pattern= instead")
    def parse(cls, s: str, /, *, format: str) -> Date: ...
    def replace(
        self, *, year: int = ..., month: int = ..., day: int = ...
    ) -> Self: ...
    @overload
    def add(
        self, *, years: int = 0, months: int = 0, weeks: int = 0, days: int = 0
    ) -> Self: ...
    @overload
    def add(self, delta: ItemizedDateDelta, /) -> Self: ...
    @overload
    def subtract(
        self, *, years: int = 0, months: int = 0, weeks: int = 0, days: int = 0
    ) -> Self: ...
    @overload
    def subtract(self, delta: ItemizedDateDelta, /) -> Self: ...
    @overload
    def since(
        self,
        other: Date,
        /,
        *,
        total: Literal["years", "months", "weeks", "days"],
    ) -> float: ...
    @overload
    def since(
        self,
        other: Date,
        /,
        *,
        in_units: Sequence[Literal["years", "months", "weeks", "days"]],
        round_mode: Literal[
            "ceil",
            "expand",
            "floor",
            "trunc",
            "half_ceil",
            "half_expand",
            "half_floor",
            "half_trunc",
            "half_even",
        ] = ...,
        round_increment: int = ...,
    ) -> ItemizedDateDelta: ...
    @overload
    def until(
        self,
        other: Date,
        /,
        *,
        total: Literal["years", "months", "weeks", "days"],
    ) -> float: ...
    @overload
    def until(
        self,
        other: Date,
        /,
        *,
        in_units: Sequence[Literal["years", "months", "weeks", "days"]],
        round_mode: Literal[
            "ceil",
            "expand",
            "floor",
            "trunc",
            "half_ceil",
            "half_expand",
            "half_floor",
            "half_trunc",
            "half_even",
        ] = ...,
        round_increment: int = ...,
    ) -> ItemizedDateDelta: ...
    def __add__(self, p: ItemizedDateDelta, /) -> Self: ...
    def __sub__(self, d: ItemizedDateDelta, /) -> Self: ...

@final
class YearMonth(_DateOrTimeMixin):
    @overload
    def __init__(self, year: int, month: int) -> None: ...
    @overload
    def __init__(self, iso_string: str, /) -> None: ...
    @property
    def year(self) -> int: ...
    @property
    def month(self) -> int: ...
    def replace(self, /, *, year: int = ..., month: int = ...) -> Self: ...
    def on_day(self, day: int, /) -> Date: ...
    def days_in_month(self) -> int: ...
    def days_in_year(self) -> int: ...
    def in_leap_year(self) -> bool: ...
    def add(self, *, years: int = 0, months: int = 0) -> Self: ...
    def subtract(self, *, years: int = 0, months: int = 0) -> Self: ...

@final
class MonthDay(_DateOrTimeMixin):
    @overload
    def __init__(self, month: int, day: int) -> None: ...
    @overload
    def __init__(self, iso_string: str, /) -> None: ...
    @property
    def month(self) -> int: ...
    @property
    def day(self) -> int: ...
    def replace(self, *, month: int = ..., day: int = ...) -> Self: ...
    def in_year(self, year: int, /) -> Date: ...
    @deprecated("use is_leap_day() instead")
    def is_leap(self) -> bool: ...
    def is_leap_day(self) -> bool: ...

@final
class IsoWeekDate(_DateOrTimeMixin):
    @overload
    def __init__(self, year: int, week: int, weekday: Weekday) -> None: ...
    @overload
    def __init__(self, iso_string: str, /) -> None: ...
    MIN: ClassVar[Self]
    MAX: ClassVar[Self]
    @property
    def year(self) -> int: ...
    @property
    def week(self) -> int: ...
    @property
    def weekday(self) -> Weekday: ...
    def date(self) -> Date: ...
    def weeks_in_year(self) -> int: ...
    def replace(
        self, /, *, year: int = ..., week: int = ..., weekday: Weekday = ...
    ) -> Self: ...
    def format_iso(self, *, basic: bool = False) -> str: ...

@final
class Time(_DateOrTimeMixin):
    @overload
    def __init__(self, iso_string: str, /) -> None: ...
    @overload
    def __init__(self, py_time: _time, /) -> None: ...
    @overload
    def __init__(
        self,
        hour: int = 0,
        minute: int = 0,
        second: int = 0,
        *,
        nanosecond: int = 0,
    ) -> None: ...
    MIDNIGHT: ClassVar[Self]
    NOON: ClassVar[Self]
    @property
    def hour(self) -> int: ...
    @property
    def minute(self) -> int: ...
    @property
    def second(self) -> int: ...
    @property
    def nanosecond(self) -> int: ...
    def on(self, d: Date, /) -> PlainDateTime: ...
    def to_stdlib(self) -> _time: ...
    def replace(
        self,
        *,
        hour: int = ...,
        minute: int = ...,
        second: int = ...,
        nanosecond: int = ...,
    ) -> Self: ...
    @overload
    def round(
        self,
        delta: TimeDelta,
        /,
        *,
        mode: Literal[
            "ceil",
            "expand",
            "floor",
            "trunc",
            "half_ceil",
            "half_expand",
            "half_floor",
            "half_trunc",
            "half_even",
        ] = "half_even",
    ) -> Self: ...
    @overload
    def round(
        self,
        unit: Literal[
            "hour",
            "minute",
            "second",
            "millisecond",
            "microsecond",
            "nanosecond",
        ] = "second",
        /,
        *,
        increment: int = 1,
        mode: Literal[
            "ceil",
            "expand",
            "floor",
            "trunc",
            "half_ceil",
            "half_expand",
            "half_floor",
            "half_trunc",
            "half_even",
        ] = "half_even",
    ) -> Self: ...
    def format_iso(
        self,
        *,
        unit: Literal[
            "hour",
            "minute",
            "second",
            "millisecond",
            "microsecond",
            "nanosecond",
            "auto",
        ] = "auto",
        basic: bool = False,
    ) -> str: ...
    def format(self, pattern: str, /) -> str: ...
    def __format__(self, spec: str, /) -> str: ...
    @overload
    @classmethod
    def parse(cls, s: str, /, *, pattern: str) -> Time: ...
    @overload
    @classmethod
    @deprecated("use pattern= instead")
    def parse(cls, s: str, /, *, format: str) -> Time: ...

@type_check_only
class _DeltaMixin(_ISOMixin):
    ZERO: ClassVar[Self]
    def __bool__(self) -> bool: ...
    def __neg__(self) -> Self: ...
    def __pos__(self) -> Self: ...
    def __abs__(self) -> Self: ...
    def __mul__(self, other: int, /) -> Self: ...
    def __rmul__(self, other: int, /) -> Self: ...

@final
class TimeDelta(_DeltaMixin, _OrderMixin):
    @overload
    def __init__(self, iso_string: str, /) -> None: ...
    @overload
    def __init__(self, py_timedelta: _timedelta, /) -> None: ...
    @overload
    def __init__(
        self,
        *,
        weeks: float = 0,
        days: float = 0,
        hours: float = 0,
        minutes: float = 0,
        seconds: float = 0,
        milliseconds: float = 0,
        microseconds: float = 0,
        nanoseconds: int = 0,
        days_assumed_24h_ok: bool = ...,
    ) -> None: ...
    @overload
    def total(
        self,
        unit: Literal["years", "months"],
        /,
        *,
        relative_to: (
            ZonedDateTime | PlainDateTime | OffsetDateTime
        ),  # required for years/months
        days_assumed_24h_ok: bool = ...,
    ) -> float: ...
    @overload
    def total(
        self,
        unit: Literal[
            "weeks",
            "days",
            "hours",
            "minutes",
            "seconds",
            "milliseconds",
            "microseconds",
        ],
        /,
        *,
        relative_to: ZonedDateTime | PlainDateTime | OffsetDateTime = ...,
        days_assumed_24h_ok: bool = ...,
    ) -> float: ...
    @overload
    def total(
        self,
        unit: Literal["nanoseconds"],
        /,
        *,
        relative_to: ZonedDateTime | PlainDateTime | OffsetDateTime = ...,
        days_assumed_24h_ok: bool = ...,
    ) -> int: ...
    @overload
    def in_units(
        self,
        units: Sequence[
            Literal[
                "years",
                "months",
                "weeks",
                "days",
                "hours",
                "minutes",
                "seconds",
                "nanoseconds",
            ]
        ],
        /,
        *,
        round_mode: Literal[
            "ceil",
            "expand",
            "floor",
            "trunc",
            "half_ceil",
            "half_expand",
            "half_floor",
            "half_trunc",
            "half_even",
        ] = "trunc",
        round_increment: int = ...,
        relative_to: ZonedDateTime | PlainDateTime | OffsetDateTime,
        days_assumed_24h_ok: bool = ...,
    ) -> ItemizedDelta: ...
    @overload
    def in_units(
        self,
        units: Sequence[
            Literal[
                "weeks",
                "days",
                "hours",
                "minutes",
                "seconds",
                "nanoseconds",
            ]
        ],
        /,
        *,
        round_mode: Literal[
            "ceil",
            "expand",
            "floor",
            "trunc",
            "half_ceil",
            "half_expand",
            "half_floor",
            "half_trunc",
            "half_even",
        ] = "trunc",
        round_increment: int = ...,
        relative_to: ZonedDateTime | PlainDateTime | OffsetDateTime = ...,
        days_assumed_24h_ok: bool = ...,
    ) -> ItemizedDelta: ...
    def to_stdlib(self) -> _timedelta: ...
    @overload
    def round(
        self,
        unit: Literal[
            "week",
            "day",
            "hour",
            "minute",
            "second",
            "millisecond",
            "microsecond",
            "nanosecond",
        ] = "second",
        /,
        *,
        increment: int = 1,
        mode: Literal[
            "ceil",
            "expand",
            "floor",
            "trunc",
            "half_ceil",
            "half_expand",
            "half_floor",
            "half_trunc",
            "half_even",
        ] = "half_even",
        days_assumed_24h_ok: bool = ...,
    ) -> Self: ...
    @overload
    def round(
        self,
        other: Self,
        /,
        *,
        mode: Literal[
            "ceil",
            "expand",
            "floor",
            "trunc",
            "half_ceil",
            "half_expand",
            "half_floor",
            "half_trunc",
            "half_even",
        ] = "half_even",
        days_assumed_24h_ok: bool = ...,
    ) -> Self: ...
    @overload
    def add(self, other: TimeDelta, /) -> Self: ...
    @overload
    def add(
        self,
        *,
        weeks: float = ...,
        days: float = ...,
        hours: float = ...,
        minutes: float = ...,
        seconds: float = ...,
        milliseconds: float = ...,
        microseconds: float = ...,
        nanoseconds: int = ...,
    ) -> Self: ...
    @overload
    def subtract(self, other: TimeDelta, /) -> Self: ...
    @overload
    def subtract(
        self,
        *,
        weeks: float = ...,
        days: float = ...,
        hours: float = ...,
        minutes: float = ...,
        seconds: float = ...,
        milliseconds: float = ...,
        microseconds: float = ...,
        nanoseconds: int = ...,
    ) -> Self: ...
    @overload
    def __add__(self, other: Self, /) -> Self: ...
    @overload
    def __add__(self, other: Instant, /) -> Instant: ...
    @overload
    def __add__(self, other: PlainDateTime, /) -> PlainDateTime: ...
    @overload
    def __add__(self, other: OffsetDateTime, /) -> OffsetDateTime: ...
    @overload
    def __add__(self, other: ZonedDateTime, /) -> ZonedDateTime: ...
    def __sub__(self, other: Self, /) -> Self: ...
    @override
    def __mul__(self, other: float, /) -> Self: ...
    @override
    def __rmul__(self, other: float, /) -> Self: ...
    @overload
    def __truediv__(self, other: float, /) -> Self: ...
    @overload
    def __truediv__(self, other: Self, /) -> float: ...
    def __floordiv__(self, other: Self, /) -> int: ...
    def __mod__(self, other: Self, /) -> Self: ...

@final
class ItemizedDelta(
    Mapping[
        Literal[
            "years",
            "months",
            "weeks",
            "days",
            "hours",
            "minutes",
            "seconds",
            "nanoseconds",
        ],
        int,
    ]
):
    @overload
    def __init__(self, iso_string: str, /) -> None: ...
    @overload
    def __init__(
        self,
        *,
        years: int = ...,
        months: int = ...,
        weeks: int = ...,
        days: int = ...,
        hours: int = ...,
        minutes: int = ...,
        seconds: int = ...,
        nanoseconds: int = ...,
    ) -> None: ...
    @classmethod
    def parse_iso(cls, s: str, /) -> Self: ...
    def format_iso(self, *, lowercase_units: bool = False) -> str: ...
    def replace(
        self,
        *,
        years: int | None = ...,
        months: int | None = ...,
        weeks: int | None = ...,
        days: int | None = ...,
        hours: int | None = ...,
        minutes: int | None = ...,
        seconds: int | None = ...,
        nanoseconds: int | None = ...,
    ) -> Self: ...
    def in_units(
        self,
        units: Sequence[
            Literal[
                "years",
                "months",
                "weeks",
                "days",
                "hours",
                "minutes",
                "seconds",
                "nanoseconds",
            ]
        ],
        /,
        *,
        relative_to: ZonedDateTime | PlainDateTime | OffsetDateTime,
        round_mode: Literal[
            "ceil",
            "expand",
            "floor",
            "trunc",
            "half_ceil",
            "half_expand",
            "half_floor",
            "half_trunc",
            "half_even",
        ] = ...,
        round_increment: int = ...,
    ) -> ItemizedDelta: ...
    def date_and_time_parts(
        self,
    ) -> tuple[ItemizedDateDelta | None, TimeDelta | None]: ...
    @deprecated("use strict_eq() instead")
    def exact_eq(self, other: Self, /) -> bool: ...
    def strict_eq(self, other: Self, /) -> bool: ...
    @overload
    def add(
        self,
        other: ItemizedDelta | ItemizedDateDelta,
        /,
        *,
        relative_to: ZonedDateTime,
        in_units: Sequence[
            Literal[
                "years",
                "months",
                "weeks",
                "days",
                "hours",
                "minutes",
                "seconds",
                "nanoseconds",
            ]
        ],
        round_mode: Literal[
            "ceil",
            "expand",
            "floor",
            "trunc",
            "half_ceil",
            "half_expand",
            "half_floor",
            "half_trunc",
            "half_even",
        ] = ...,
        round_increment: int = ...,
    ) -> ItemizedDelta: ...
    @overload
    def add(
        self,
        /,
        *,
        years: int = ...,
        months: int = ...,
        weeks: int = ...,
        days: int = ...,
        hours: int = ...,
        minutes: int = ...,
        seconds: int = ...,
        nanoseconds: int = ...,
        relative_to: ZonedDateTime,
        in_units: Sequence[
            Literal[
                "years",
                "months",
                "weeks",
                "days",
                "hours",
                "minutes",
                "seconds",
                "nanoseconds",
            ]
        ],
        round_mode: Literal[
            "ceil",
            "expand",
            "floor",
            "trunc",
            "half_ceil",
            "half_expand",
            "half_floor",
            "half_trunc",
            "half_even",
        ] = ...,
        round_increment: int = ...,
    ) -> ItemizedDelta: ...
    @overload
    def add(
        self,
        /,
        *,
        years: int = ...,
        months: int = ...,
        weeks: int = ...,
        days: int = ...,
        hours: int = ...,
        minutes: int = ...,
        seconds: int = ...,
        nanoseconds: int = ...,
        cal_unit_composition_ok: bool = ...,
    ) -> ItemizedDelta: ...
    @overload
    def add(
        self,
        other: ItemizedDelta | ItemizedDateDelta,
        /,
        *,
        cal_unit_composition_ok: bool = ...,
    ) -> ItemizedDelta: ...
    @overload
    def subtract(
        self,
        other: ItemizedDelta | ItemizedDateDelta,
        /,
        *,
        relative_to: ZonedDateTime,
        in_units: Sequence[
            Literal[
                "years",
                "months",
                "weeks",
                "days",
                "hours",
                "minutes",
                "seconds",
                "nanoseconds",
            ]
        ],
        round_mode: Literal[
            "ceil",
            "expand",
            "floor",
            "trunc",
            "half_ceil",
            "half_expand",
            "half_floor",
            "half_trunc",
            "half_even",
        ] = ...,
        round_increment: int = ...,
    ) -> ItemizedDelta: ...
    @overload
    def subtract(
        self,
        /,
        *,
        years: int = ...,
        months: int = ...,
        weeks: int = ...,
        days: int = ...,
        hours: int = ...,
        minutes: int = ...,
        seconds: int = ...,
        nanoseconds: int = ...,
        relative_to: ZonedDateTime,
        in_units: Sequence[
            Literal[
                "years",
                "months",
                "weeks",
                "days",
                "hours",
                "minutes",
                "seconds",
                "nanoseconds",
            ]
        ],
        round_mode: Literal[
            "ceil",
            "expand",
            "floor",
            "trunc",
            "half_ceil",
            "half_expand",
            "half_floor",
            "half_trunc",
            "half_even",
        ] = ...,
        round_increment: int = ...,
    ) -> ItemizedDelta: ...
    @overload
    def subtract(
        self,
        /,
        *,
        years: int = ...,
        months: int = ...,
        weeks: int = ...,
        days: int = ...,
        hours: int = ...,
        minutes: int = ...,
        seconds: int = ...,
        nanoseconds: int = ...,
        cal_unit_composition_ok: bool = ...,
    ) -> ItemizedDelta: ...
    @overload
    def subtract(
        self,
        other: ItemizedDelta | ItemizedDateDelta,
        /,
        *,
        cal_unit_composition_ok: bool = ...,
    ) -> ItemizedDelta: ...
    @overload
    def total(
        self,
        unit: Literal[
            "years",
            "months",
            "weeks",
            "days",
            "hours",
            "minutes",
            "seconds",
            "milliseconds",
            "microseconds",
        ],
        /,
        *,
        relative_to: ZonedDateTime | PlainDateTime | OffsetDateTime,
    ) -> float: ...
    @overload
    def total(
        self,
        unit: Literal["nanoseconds"],
        /,
        *,
        relative_to: ZonedDateTime | PlainDateTime | OffsetDateTime,
    ) -> int: ...
    def __iter__(
        self,
    ) -> Iterator[
        Literal[
            "years",
            "months",
            "weeks",
            "days",
            "hours",
            "minutes",
            "seconds",
            "nanoseconds",
        ]
    ]: ...
    def __len__(self) -> int: ...
    def __getitem__(
        self,
        item: Literal[
            "years",
            "months",
            "weeks",
            "days",
            "hours",
            "minutes",
            "seconds",
            "nanoseconds",
        ],
    ) -> int: ...
    def __abs__(self) -> Self: ...
    def __neg__(self) -> Self: ...
    @overload
    def __add__(self, other: ItemizedDelta, /) -> ItemizedDelta: ...
    @overload
    def __add__(self, other: ItemizedDateDelta, /) -> ItemizedDelta: ...
    @overload
    def __add__(self, other: ZonedDateTime, /) -> ZonedDateTime: ...
    @overload
    def __add__(self, other: PlainDateTime, /) -> PlainDateTime: ...
    @overload
    def __add__(self, other: OffsetDateTime, /) -> OffsetDateTime: ...
    @overload
    def __sub__(self, other: ItemizedDelta, /) -> ItemizedDelta: ...
    @overload
    def __sub__(self, other: ItemizedDateDelta, /) -> ItemizedDelta: ...
    def __bool__(self) -> bool: ...
    def sign(self) -> Literal[1, 0, -1]: ...

@final
class ItemizedDateDelta(
    Mapping[Literal["years", "months", "weeks", "days"], int]
):
    @overload
    def __init__(self, iso_string: str, /) -> None: ...
    @overload
    def __init__(
        self,
        *,
        years: int = ...,
        months: int = ...,
        weeks: int = ...,
        days: int = ...,
    ) -> None: ...
    def sign(self) -> Literal[1, 0, -1]: ...
    def format_iso(self, *, lowercase_units: bool = False) -> str: ...
    @classmethod
    def parse_iso(cls, s: str, /) -> Self: ...
    def replace(
        self,
        *,
        years: int | None = ...,
        months: int | None = ...,
        weeks: int | None = ...,
        days: int | None = ...,
    ) -> Self: ...
    def in_units(
        self,
        units: Sequence[Literal["years", "months", "weeks", "days"]],
        /,
        *,
        relative_to: Date,
        round_mode: Literal[
            "ceil",
            "expand",
            "floor",
            "trunc",
            "half_ceil",
            "half_expand",
            "half_floor",
            "half_trunc",
            "half_even",
        ] = ...,
        round_increment: int = ...,
    ) -> ItemizedDateDelta: ...
    @deprecated("use strict_eq() instead")
    def exact_eq(self, other: Self, /) -> bool: ...
    def strict_eq(self, other: Self, /) -> bool: ...
    @overload
    def add(
        self,
        other: ItemizedDateDelta,
        /,
        *,
        relative_to: Date,
        in_units: Sequence[Literal["years", "months", "weeks", "days"]],
        round_mode: Literal[
            "ceil",
            "expand",
            "floor",
            "trunc",
            "half_ceil",
            "half_expand",
            "half_floor",
            "half_trunc",
            "half_even",
        ] = ...,
        round_increment: int = ...,
    ) -> ItemizedDateDelta: ...
    @overload
    def add(
        self,
        other: ItemizedDelta,
        /,
        *,
        relative_to: ZonedDateTime | PlainDateTime | OffsetDateTime,
        in_units: Sequence[DeltaUnitStr],
        round_mode: Literal[
            "ceil",
            "expand",
            "floor",
            "trunc",
            "half_ceil",
            "half_expand",
            "half_floor",
            "half_trunc",
            "half_even",
        ] = ...,
        round_increment: int = ...,
    ) -> ItemizedDelta: ...
    @overload
    def add(
        self,
        /,
        *,
        years: int = ...,
        months: int = ...,
        weeks: int = ...,
        days: int = ...,
        relative_to: Date,
        in_units: Sequence[Literal["years", "months", "weeks", "days"]],
        round_mode: Literal[
            "ceil",
            "expand",
            "floor",
            "trunc",
            "half_ceil",
            "half_expand",
            "half_floor",
            "half_trunc",
            "half_even",
        ] = ...,
        round_increment: int = ...,
    ) -> ItemizedDateDelta: ...
    @overload
    def add(
        self,
        /,
        *,
        years: int = ...,
        months: int = ...,
        weeks: int = ...,
        days: int = ...,
        cal_unit_composition_ok: bool = ...,
    ) -> ItemizedDateDelta: ...
    @overload
    def add(
        self,
        other: ItemizedDateDelta,
        /,
        *,
        cal_unit_composition_ok: bool = ...,
    ) -> ItemizedDateDelta: ...
    @overload
    def add(
        self,
        other: ItemizedDelta,
        /,
        *,
        cal_unit_composition_ok: bool = ...,
    ) -> ItemizedDelta: ...
    @overload
    def subtract(
        self,
        other: ItemizedDateDelta,
        /,
        *,
        relative_to: Date,
        in_units: Sequence[Literal["years", "months", "weeks", "days"]],
        round_mode: Literal[
            "ceil",
            "expand",
            "floor",
            "trunc",
            "half_ceil",
            "half_expand",
            "half_floor",
            "half_trunc",
            "half_even",
        ] = ...,
        round_increment: int = ...,
    ) -> ItemizedDateDelta: ...
    @overload
    def subtract(
        self,
        other: ItemizedDelta,
        /,
        *,
        relative_to: ZonedDateTime | PlainDateTime | OffsetDateTime,
        in_units: Sequence[DeltaUnitStr],
        round_mode: Literal[
            "ceil",
            "expand",
            "floor",
            "trunc",
            "half_ceil",
            "half_expand",
            "half_floor",
            "half_trunc",
            "half_even",
        ] = ...,
        round_increment: int = ...,
    ) -> ItemizedDelta: ...
    @overload
    def subtract(
        self,
        /,
        *,
        years: int = ...,
        months: int = ...,
        weeks: int = ...,
        days: int = ...,
        relative_to: Date,
        in_units: Sequence[Literal["years", "months", "weeks", "days"]],
        round_mode: Literal[
            "ceil",
            "expand",
            "floor",
            "trunc",
            "half_ceil",
            "half_expand",
            "half_floor",
            "half_trunc",
            "half_even",
        ] = ...,
        round_increment: int = ...,
    ) -> ItemizedDateDelta: ...
    @overload
    def subtract(
        self,
        /,
        *,
        years: int = ...,
        months: int = ...,
        weeks: int = ...,
        days: int = ...,
        cal_unit_composition_ok: bool = ...,
    ) -> ItemizedDateDelta: ...
    @overload
    def subtract(
        self,
        other: ItemizedDateDelta,
        /,
        *,
        cal_unit_composition_ok: bool = ...,
    ) -> ItemizedDateDelta: ...
    @overload
    def subtract(
        self,
        other: ItemizedDelta,
        /,
        *,
        cal_unit_composition_ok: bool = ...,
    ) -> ItemizedDelta: ...
    def total(
        self,
        unit: Literal["years", "months", "weeks", "days"],
        /,
        *,
        relative_to: Date,
    ) -> float: ...
    def __iter__(
        self,
    ) -> Iterator[Literal["years", "months", "weeks", "days"]]: ...
    def __len__(self) -> int: ...
    def __getitem__(
        self, item: Literal["years", "months", "weeks", "days"]
    ) -> int: ...
    def __abs__(self) -> Self: ...
    def __neg__(self) -> Self: ...
    @overload
    def __add__(self, other: ItemizedDateDelta, /) -> ItemizedDateDelta: ...
    @overload
    def __add__(self, other: ItemizedDelta, /) -> ItemizedDelta: ...
    @overload
    def __add__(self, other: Date, /) -> Date: ...
    @overload
    def __add__(self, other: ZonedDateTime, /) -> ZonedDateTime: ...
    @overload
    def __add__(self, other: PlainDateTime, /) -> PlainDateTime: ...
    @overload
    def __add__(self, other: OffsetDateTime, /) -> OffsetDateTime: ...
    @overload
    def __sub__(self, other: ItemizedDateDelta, /) -> ItemizedDateDelta: ...
    @overload
    def __sub__(self, other: ItemizedDelta, /) -> ItemizedDelta: ...
    def __bool__(self) -> bool: ...

class _LocalTime(ABC):
    @property
    def year(self) -> int: ...
    @property
    def month(self) -> int: ...
    @property
    def day(self) -> int: ...
    @property
    def hour(self) -> int: ...
    @property
    def minute(self) -> int: ...
    @property
    def second(self) -> int: ...
    @property
    def nanosecond(self) -> int: ...
    def date(self) -> Date: ...
    def time(self) -> Time: ...
    def day_of_year(self) -> int: ...
    def days_in_month(self) -> int: ...
    def days_in_year(self) -> int: ...
    def in_leap_year(self) -> bool: ...
    def start_of(
        self,
        unit: Literal[
            "year",
            "month",
            "week_mon",
            "week_sun",
            "day",
            "hour",
            "minute",
            "second",
        ],
        /,
    ) -> Self: ...
    def end_of(
        self,
        unit: Literal[
            "year",
            "month",
            "week_mon",
            "week_sun",
            "day",
            "hour",
            "minute",
            "second",
        ],
        /,
    ) -> Self: ...
    @overload
    def since(
        self,
        b: Self,
        /,
        *,
        total: Literal[
            "years",
            "months",
            "weeks",
            "days",
            "hours",
            "minutes",
            "seconds",
            "milliseconds",
            "microseconds",
        ],
    ) -> float: ...
    @overload
    def since(
        self,
        b: Self,
        /,
        *,
        total: Literal["nanoseconds"],
    ) -> int: ...
    @overload
    def since(
        self,
        b: Self,
        /,
        *,
        in_units: Sequence[
            Literal[
                "years",
                "months",
                "weeks",
                "days",
                "hours",
                "minutes",
                "seconds",
                "nanoseconds",
            ]
        ],
        round_mode: Literal[
            "ceil",
            "expand",
            "floor",
            "trunc",
            "half_ceil",
            "half_expand",
            "half_floor",
            "half_trunc",
            "half_even",
        ] = ...,
        round_increment: int = ...,
    ) -> ItemizedDelta: ...
    @overload
    def until(
        self,
        b: Self,
        /,
        *,
        total: Literal[
            "years",
            "months",
            "weeks",
            "days",
            "hours",
            "minutes",
            "seconds",
            "milliseconds",
            "microseconds",
        ],
    ) -> float: ...
    @overload
    def until(
        self,
        b: Self,
        /,
        *,
        total: Literal["nanoseconds"],
    ) -> int: ...
    @overload
    def until(
        self,
        b: Self,
        /,
        *,
        in_units: Sequence[
            Literal[
                "years",
                "months",
                "weeks",
                "days",
                "hours",
                "minutes",
                "seconds",
                "nanoseconds",
            ]
        ],
        round_mode: Literal[
            "ceil",
            "expand",
            "floor",
            "trunc",
            "half_ceil",
            "half_expand",
            "half_floor",
            "half_trunc",
            "half_even",
        ] = ...,
        round_increment: int = ...,
    ) -> ItemizedDelta: ...
    @overload
    def round(
        self,
        delta: TimeDelta,
        /,
        *,
        mode: Literal[
            "ceil",
            "expand",
            "floor",
            "trunc",
            "half_ceil",
            "half_expand",
            "half_floor",
            "half_trunc",
            "half_even",
        ] = "half_even",
    ) -> Self: ...
    @overload
    def round(
        self,
        unit: Literal[
            "day",
            "hour",
            "minute",
            "second",
            "millisecond",
            "microsecond",
            "nanosecond",
        ] = "second",
        /,
        *,
        increment: int = 1,
        mode: Literal[
            "ceil",
            "expand",
            "floor",
            "trunc",
            "half_ceil",
            "half_expand",
            "half_floor",
            "half_trunc",
            "half_even",
        ] = "half_even",
    ) -> Self: ...

class _ExactTime(ABC):
    def timestamp(
        self,
        *,
        unit: Literal["second", "millisecond", "microsecond", "nanosecond"] = "second",
    ) -> int: ...
    @deprecated("use timestamp(unit='millisecond') instead")
    def timestamp_millis(self) -> int: ...
    @deprecated("use timestamp(unit='nanosecond') instead")
    def timestamp_nanos(self) -> int: ...
    @overload
    def to_fixed_offset(self, /) -> OffsetDateTime: ...
    @overload
    def to_fixed_offset(
        self, offset: int | TimeDelta, /
    ) -> OffsetDateTime: ...
    def to_tz(self, tz: str | SYSTEM_TZ, /) -> ZonedDateTime: ...  # type: ignore[valid-type]
    @deprecated("use to_tz(SYSTEM_TZ) instead")
    def to_system_tz(self) -> ZonedDateTime: ...
    def difference(self, other: _ExactTime, /) -> TimeDelta: ...
    def __lt__(self, other: _ExactTime, /) -> bool: ...
    def __le__(self, other: _ExactTime, /) -> bool: ...
    def __gt__(self, other: _ExactTime, /) -> bool: ...
    def __ge__(self, other: _ExactTime, /) -> bool: ...
    @deprecated("use strict_eq() instead")
    def exact_eq(self, other: Self, /) -> bool: ...
    def strict_eq(self, other: Self, /) -> bool: ...
    def __add__(self, delta: TimeDelta, /) -> Self: ...
    @overload
    def __sub__(self, other: _ExactTime) -> TimeDelta: ...
    @overload
    def __sub__(self, other: TimeDelta, /) -> Self: ...

class _ExactAndLocalTime(_ExactTime, _LocalTime, ABC):
    def to_instant(self) -> Instant: ...
    def to_plain(self) -> PlainDateTime: ...
    @property
    def offset(self) -> TimeDelta: ...

@type_check_only
class _PyDateTimeMixin(_ISOMixin):
    def to_stdlib(self) -> _datetime: ...
    def format_iso(
        self,
        *,
        unit: Literal[
            "hour",
            "minute",
            "second",
            "millisecond",
            "microsecond",
            "nanosecond",
            "auto",
        ] = "auto",
        basic: bool = False,
        sep: Literal["T", " "] = "T",
    ) -> str: ...

@final
class Instant(_PyDateTimeMixin, _ExactTime):
    @overload
    def __init__(self, iso_string: str, /) -> None: ...
    @overload
    def __init__(self, py_datetime: _datetime, /) -> None: ...
    @classmethod
    def from_utc(
        cls,
        year: int,
        month: int,
        day: int,
        hour: int = 0,
        minute: int = 0,
        second: int = 0,
        *,
        nanosecond: int = 0,
    ) -> Self: ...
    MIN: ClassVar[Self]
    MAX: ClassVar[Self]
    @classmethod
    def now(cls) -> Self: ...
    @overload
    @classmethod
    def from_timestamp(
        cls,
        i: int | float,
        /,
        *,
        unit: Literal["second"] = "second",
    ) -> Self: ...
    @overload
    @classmethod
    def from_timestamp(
        cls,
        i: int,
        /,
        *,
        unit: Literal["millisecond", "microsecond", "nanosecond"],
    ) -> Self: ...
    @classmethod
    @deprecated("use from_timestamp(..., unit='millisecond') instead")
    def from_timestamp_millis(cls, i: int, /) -> Self: ...
    @classmethod
    @deprecated("use from_timestamp(..., unit='nanosecond') instead")
    def from_timestamp_nanos(cls, i: int, /) -> Self: ...
    def format_rfc2822(self) -> str: ...
    @classmethod
    def parse_rfc2822(cls, s: str, /) -> Self: ...
    def format(self, pattern: str, /) -> str: ...
    def __format__(self, spec: str, /) -> str: ...
    @overload
    @classmethod
    def parse(cls, s: str, /, *, pattern: str) -> Instant: ...
    @overload
    @classmethod
    @deprecated("use pattern= instead")
    def parse(cls, s: str, /, *, format: str) -> Instant: ...
    @overload
    def add(self, d: TimeDelta, /) -> Self: ...
    @overload
    def add(
        self,
        *,
        weeks: float = 0,
        days: float = 0,
        hours: float = 0,
        minutes: float = 0,
        seconds: float = 0,
        milliseconds: float = 0,
        microseconds: float = 0,
        nanoseconds: int = 0,
        days_assumed_24h_ok: bool = False,
    ) -> Self: ...
    @overload
    def subtract(self, d: TimeDelta, /) -> Self: ...
    @overload
    def subtract(
        self,
        *,
        weeks: float = 0,
        days: float = 0,
        hours: float = 0,
        minutes: float = 0,
        seconds: float = 0,
        milliseconds: float = 0,
        microseconds: float = 0,
        nanoseconds: int = 0,
        days_assumed_24h_ok: bool = False,
    ) -> Self: ...
    @overload
    def round(
        self,
        delta: TimeDelta,
        /,
        *,
        mode: Literal[
            "ceil",
            "expand",
            "floor",
            "trunc",
            "half_ceil",
            "half_expand",
            "half_floor",
            "half_trunc",
            "half_even",
        ] = "half_even",
    ) -> Self: ...
    @overload
    def round(
        self,
        unit: Literal[
            "hour",
            "minute",
            "second",
            "millisecond",
            "microsecond",
            "nanosecond",
        ] = "second",
        /,
        *,
        increment: int = 1,
        mode: Literal[
            "ceil",
            "expand",
            "floor",
            "trunc",
            "half_ceil",
            "half_expand",
            "half_floor",
            "half_trunc",
            "half_even",
        ] = "half_even",
    ) -> Self: ...

@final
class OffsetDateTime(_PyDateTimeMixin, _ExactAndLocalTime):
    @overload
    def __init__(self, py_datetime: _datetime, /) -> None: ...
    @overload
    def __init__(self, iso_string: str, /) -> None: ...
    @overload
    def __init__(
        self,
        year: int,
        month: int,
        day: int,
        hour: int = 0,
        minute: int = 0,
        second: int = 0,
        *,
        nanosecond: int = 0,
        offset: int | TimeDelta,
    ) -> None: ...
    @classmethod
    def now(
        cls,
        offset: int | TimeDelta,
        /,
        *,
        stale_offset_ok: bool = ...,
    ) -> Self: ...
    @classmethod
    @deprecated(
        "use Instant.from_timestamp(...).to_fixed_offset(...) instead"
    )
    def from_timestamp(
        cls,
        i: int | float,
        /,
        *,
        offset: int | TimeDelta,
        stale_offset_ok: bool = ...,
    ) -> Self: ...
    @classmethod
    @deprecated(
        "use Instant.from_timestamp(..., unit='millisecond').to_fixed_offset(...) instead"
    )
    def from_timestamp_millis(
        cls,
        i: int,
        /,
        *,
        offset: int | TimeDelta,
        stale_offset_ok: bool = ...,
    ) -> Self: ...
    @classmethod
    @deprecated(
        "use Instant.from_timestamp(..., unit='nanosecond').to_fixed_offset(...) instead"
    )
    def from_timestamp_nanos(
        cls,
        i: int,
        /,
        *,
        offset: int | TimeDelta,
        stale_offset_ok: bool = ...,
    ) -> Self: ...
    def format_rfc2822(self) -> str: ...
    @classmethod
    def parse_rfc2822(cls, s: str, /) -> Self: ...
    def format(self, pattern: str, /) -> str: ...
    def __format__(self, spec: str, /) -> str: ...
    @overload
    @classmethod
    def parse(cls, s: str, /, *, pattern: str) -> OffsetDateTime: ...
    @overload
    @classmethod
    @deprecated("use pattern= instead")
    def parse(cls, s: str, /, *, format: str) -> OffsetDateTime: ...
    def replace(
        self,
        *,
        year: int = ...,
        month: int = ...,
        day: int = ...,
        hour: int = ...,
        minute: int = ...,
        second: int = ...,
        nanosecond: int = ...,
        offset: int | TimeDelta = ...,
        stale_offset_ok: bool = ...,
    ) -> Self: ...
    def replace_date(
        self,
        d: Date,
        /,
        *,
        stale_offset_ok: bool = ...,
    ) -> Self: ...
    def replace_time(
        self,
        t: Time,
        /,
        *,
        stale_offset_ok: bool = ...,
    ) -> Self: ...
    def start_of(
        self,
        unit: Literal[
            "year",
            "month",
            "week_mon",
            "week_sun",
            "day",
            "hour",
            "minute",
            "second",
        ],
        /,
        *,
        stale_offset_ok: bool = ...,
    ) -> Self: ...
    def end_of(
        self,
        unit: Literal[
            "year",
            "month",
            "week_mon",
            "week_sun",
            "day",
            "hour",
            "minute",
            "second",
        ],
        /,
        *,
        stale_offset_ok: bool = ...,
    ) -> Self: ...
    @overload
    def add(
        self,
        *,
        years: int = 0,
        months: int = 0,
        weeks: int = 0,
        days: int = 0,
        hours: float = 0,
        minutes: float = 0,
        seconds: float = 0,
        milliseconds: float = 0,
        microseconds: float = 0,
        nanoseconds: int = 0,
        stale_offset_ok: bool = ...,
    ) -> Self: ...
    @overload
    def add(
        self,
        d: ItemizedDelta | ItemizedDateDelta | TimeDelta,
        /,
        *,
        stale_offset_ok: bool = ...,
    ) -> Self: ...
    @overload
    def subtract(
        self,
        *,
        years: int = 0,
        months: int = 0,
        weeks: int = 0,
        days: int = 0,
        hours: float = 0,
        minutes: float = 0,
        seconds: float = 0,
        milliseconds: float = 0,
        microseconds: float = 0,
        nanoseconds: int = 0,
        stale_offset_ok: bool = ...,
    ) -> Self: ...
    @overload
    def subtract(
        self,
        d: ItemizedDelta | ItemizedDateDelta | TimeDelta,
        /,
        *,
        stale_offset_ok: bool = ...,
    ) -> Self: ...
    @overload
    def round(
        self,
        delta: TimeDelta,
        /,
        *,
        mode: Literal[
            "ceil",
            "expand",
            "floor",
            "trunc",
            "half_ceil",
            "half_expand",
            "half_floor",
            "half_trunc",
            "half_even",
        ] = "half_even",
        stale_offset_ok: bool = ...,
    ) -> Self: ...
    @overload
    def round(
        self,
        unit: Literal[
            "day",
            "hour",
            "minute",
            "second",
            "millisecond",
            "microsecond",
            "nanosecond",
        ] = "second",
        /,
        *,
        increment: int = 1,
        mode: Literal[
            "ceil",
            "expand",
            "floor",
            "trunc",
            "half_ceil",
            "half_expand",
            "half_floor",
            "half_trunc",
            "half_even",
        ] = "half_even",
        stale_offset_ok: bool = ...,
    ) -> Self: ...
    def assume_tz(
        self,
        tz: str | SYSTEM_TZ,  # type: ignore[valid-type]
        /,
        *,
        offset_mismatch: Literal[
            "raise", "keep_instant", "keep_local"
        ] = "raise",
        disambiguation: Literal[
            "compatible", "raise", "earlier", "later"
        ] = ...,
    ) -> ZonedDateTime: ...
    def __add__(
        self, delta: TimeDelta | ItemizedDelta | ItemizedDateDelta, /
    ) -> Self: ...
    @overload  # type: ignore[override]
    def __sub__(self, other: _ExactTime) -> TimeDelta: ...
    @overload
    def __sub__(
        self, other: TimeDelta | ItemizedDelta | ItemizedDateDelta, /
    ) -> Self: ...

@final
class ZonedDateTime(_PyDateTimeMixin, _ExactAndLocalTime):
    @overload
    def __init__(
        self,
        iso_string: str,
        /,
        *,
        disambiguation: Literal[
            "compatible", "raise", "earlier", "later"
        ] = ...,
        offset_mismatch: Literal[
            "raise", "keep_instant", "keep_local"
        ] = "raise",
    ) -> None: ...
    @overload
    def __init__(self, py_datetime: _datetime, /) -> None: ...
    @overload
    def __init__(
        self,
        year: int,
        month: int,
        day: int,
        hour: int = 0,
        minute: int = 0,
        second: int = 0,
        *,
        nanosecond: int = 0,
        tz: str | SYSTEM_TZ,  # type: ignore[valid-type]
        disambiguation: Literal[
            "compatible", "raise", "earlier", "later"
        ] = ...,
        disambiguate: Literal[
            "compatible", "raise", "earlier", "later"
        ] = ...,
    ) -> None: ...
    @property
    @deprecated("use tz_id instead")
    def tz(self) -> str | None: ...
    @property
    def tz_id(self) -> str | None: ...
    @classmethod
    @deprecated("use ZonedDateTime(..., tz=SYSTEM_TZ) instead")
    def from_system_tz(
        cls,
        year: int,
        month: int,
        day: int,
        hour: int = 0,
        minute: int = 0,
        second: int = 0,
        *,
        nanosecond: int = 0,
        disambiguate: Literal["compatible", "raise", "earlier", "later"] = ...,
    ) -> Self: ...
    @classmethod
    def now(cls, tz: str | SYSTEM_TZ, /) -> Self: ...  # type: ignore[valid-type]
    @classmethod
    @deprecated("use now(SYSTEM_TZ) instead")
    def now_in_system_tz(cls) -> Self: ...
    @classmethod
    @deprecated("use Instant.from_timestamp(...).to_tz(...) instead")
    def from_timestamp(
        cls, i: int | float, /, *, tz: str | SYSTEM_TZ  # type: ignore[valid-type]
    ) -> Self: ...
    @classmethod
    @deprecated(
        "use Instant.from_timestamp(..., unit='millisecond').to_tz(...) instead"
    )
    def from_timestamp_millis(
        cls, i: int, /, *, tz: str | SYSTEM_TZ  # type: ignore[valid-type]
    ) -> Self: ...
    @classmethod
    @deprecated(
        "use Instant.from_timestamp(..., unit='nanosecond').to_tz(...) instead"
    )
    def from_timestamp_nanos(
        cls, i: int, /, *, tz: str | SYSTEM_TZ  # type: ignore[valid-type]
    ) -> Self: ...
    def replace(
        self,
        *,
        year: int = ...,
        month: int = ...,
        day: int = ...,
        hour: int = ...,
        minute: int = ...,
        second: int = ...,
        nanosecond: int = ...,
        tz: str | SYSTEM_TZ = ...,  # type: ignore[valid-type]
        disambiguation: Literal[
            "compatible", "raise", "earlier", "later"
        ] = ...,
        disambiguate: Literal[
            "compatible", "raise", "earlier", "later"
        ] = ...,
    ) -> Self: ...
    def replace_date(
        self,
        d: Date,
        /,
        *,
        disambiguation: Literal[
            "compatible", "raise", "earlier", "later"
        ] = ...,
        disambiguate: Literal["compatible", "raise", "earlier", "later"] = ...,
    ) -> Self: ...
    def replace_time(
        self,
        t: Time,
        /,
        *,
        disambiguation: Literal[
            "compatible", "raise", "earlier", "later"
        ] = ...,
        disambiguate: Literal["compatible", "raise", "earlier", "later"] = ...,
    ) -> Self: ...
    @overload
    def add(
        self,
        *,
        years: int = 0,
        months: int = 0,
        weeks: int = 0,
        days: int = 0,
        hours: float = 0,
        minutes: float = 0,
        seconds: float = 0,
        milliseconds: float = 0,
        microseconds: float = 0,
        nanoseconds: int = 0,
        disambiguation: Literal[
            "compatible", "raise", "earlier", "later"
        ] = ...,
        disambiguate: Literal["compatible", "raise", "earlier", "later"] = ...,
    ) -> Self: ...
    # FUTURE: allow disambiguate here for API consistency
    @overload
    def add(self, d: TimeDelta, /) -> Self: ...
    @overload
    def add(
        self,
        d: ItemizedDelta | ItemizedDateDelta,
        /,
        *,
        disambiguation: Literal[
            "compatible", "raise", "earlier", "later"
        ] = ...,
        disambiguate: Literal["compatible", "raise", "earlier", "later"] = ...,
    ) -> Self: ...
    @overload
    def subtract(
        self,
        *,
        years: int = 0,
        months: int = 0,
        weeks: int = 0,
        days: int = 0,
        hours: float = 0,
        minutes: float = 0,
        seconds: float = 0,
        milliseconds: float = 0,
        microseconds: float = 0,
        nanoseconds: int = 0,
        disambiguation: Literal[
            "compatible", "raise", "earlier", "later"
        ] = ...,
        disambiguate: Literal["compatible", "raise", "earlier", "later"] = ...,
    ) -> Self: ...
    @overload
    def subtract(self, d: TimeDelta, /) -> Self: ...
    @overload
    def subtract(
        self,
        d: ItemizedDelta | ItemizedDateDelta,
        /,
        *,
        disambiguation: Literal[
            "compatible", "raise", "earlier", "later"
        ] = ...,
        disambiguate: Literal["compatible", "raise", "earlier", "later"] = ...,
    ) -> Self: ...
    def is_ambiguous(self) -> bool: ...
    def next_transition(self) -> ZonedDateTime | None: ...
    def prev_transition(self) -> ZonedDateTime | None: ...
    def dst_offset(self) -> TimeDelta: ...
    def tz_abbrev(self) -> str: ...
    def day_length(self) -> TimeDelta: ...
    def format_iso(
        self,
        *,
        unit: Literal[
            "hour",
            "minute",
            "second",
            "millisecond",
            "microsecond",
            "nanosecond",
            "auto",
        ] = "auto",
        basic: bool = False,
        sep: Literal["T", " "] = "T",
        tz_id_display: Literal[
            "required", "never", "auto", "always"
        ] = "required",
        tz: Literal["required", "always", "never", "auto"] = ...,
    ) -> str: ...
    def format(self, pattern: str, /) -> str: ...
    def __format__(self, spec: str, /) -> str: ...
    @classmethod
    def parse_iso(
        cls,
        s: str,
        /,
        *,
        disambiguation: Literal[
            "compatible", "raise", "earlier", "later"
        ] = ...,
        offset_mismatch: Literal[
            "raise", "keep_instant", "keep_local"
        ] = "raise",
        disambiguate: Literal[
            "compatible", "raise", "earlier", "later"
        ] = ...,
    ) -> Self: ...
    @overload
    @classmethod
    def parse(
        cls,
        s: str,
        /,
        *,
        pattern: str,
        disambiguation: Literal[
            "compatible", "raise", "earlier", "later"
        ] = ...,
        offset_mismatch: Literal[
            "raise", "keep_instant", "keep_local"
        ] = "raise",
    ) -> ZonedDateTime: ...
    @overload
    @classmethod
    @deprecated("use pattern= instead")
    def parse(
        cls,
        s: str,
        /,
        *,
        format: str,
        disambiguation: Literal[
            "compatible", "raise", "earlier", "later"
        ] = ...,
        offset_mismatch: Literal[
            "raise", "keep_instant", "keep_local"
        ] = "raise",
    ) -> ZonedDateTime: ...
    def __add__(
        self,
        delta: TimeDelta | ItemizedDelta | ItemizedDateDelta,
        /,
    ) -> Self: ...
    @overload  # type: ignore[override]
    def __sub__(self, other: _ExactTime) -> TimeDelta: ...
    @overload
    def __sub__(
        self,
        other: TimeDelta | ItemizedDelta | ItemizedDateDelta,
    ) -> Self: ...

@final
class PlainDateTime(_PyDateTimeMixin, _DateOrTimeMixin, _LocalTime):
    @overload
    def __init__(self, iso_string: str, /) -> None: ...
    @overload
    def __init__(self, py_datetime: _datetime, /) -> None: ...
    @overload
    def __init__(
        self,
        year: int,
        month: int,
        day: int,
        hour: int = 0,
        minute: int = 0,
        second: int = 0,
        *,
        nanosecond: int = 0,
    ) -> None: ...
    def assume_utc(self) -> Instant: ...
    def assume_fixed_offset(
        self, offset: int | TimeDelta, /
    ) -> OffsetDateTime: ...
    def assume_tz(
        self,
        tz: str | SYSTEM_TZ,  # type: ignore[valid-type]
        /,
        *,
        disambiguation: Literal[
            "compatible", "raise", "earlier", "later"
        ] = ...,
        disambiguate: Literal["compatible", "raise", "earlier", "later"] = ...,
    ) -> ZonedDateTime: ...
    @deprecated("use assume_tz(SYSTEM_TZ) instead")
    def assume_system_tz(
        self,
        *,
        disambiguate: Literal["compatible", "raise", "earlier", "later"] = ...,
    ) -> ZonedDateTime: ...
    def format(self, pattern: str, /) -> str: ...
    def __format__(self, spec: str, /) -> str: ...
    @overload
    @classmethod
    def parse(cls, s: str, /, *, pattern: str) -> PlainDateTime: ...
    @overload
    @classmethod
    @deprecated("use pattern= instead")
    def parse(cls, s: str, /, *, format: str) -> PlainDateTime: ...
    def replace(
        self,
        *,
        year: int = ...,
        month: int = ...,
        day: int = ...,
        hour: int = ...,
        minute: int = ...,
        second: int = ...,
        nanosecond: int = ...,
    ) -> Self: ...
    def replace_date(self, d: Date, /) -> Self: ...
    def replace_time(self, t: Time, /) -> Self: ...
    @overload
    def since(
        self,
        b: Self,
        /,
        *,
        total: Literal[
            "years",
            "months",
            "weeks",
            "days",
            "hours",
            "minutes",
            "seconds",
            "milliseconds",
            "microseconds",
        ],
        naive_arithmetic_ok: bool = ...,
    ) -> float: ...
    @overload
    def since(
        self,
        b: Self,
        /,
        *,
        total: Literal["nanoseconds"],
        naive_arithmetic_ok: bool = ...,
    ) -> int: ...
    @overload
    def since(
        self,
        b: Self,
        /,
        *,
        in_units: Sequence[
            Literal[
                "years",
                "months",
                "weeks",
                "days",
                "hours",
                "minutes",
                "seconds",
                "nanoseconds",
            ]
        ],
        round_mode: Literal[
            "ceil",
            "expand",
            "floor",
            "trunc",
            "half_ceil",
            "half_expand",
            "half_floor",
            "half_trunc",
            "half_even",
        ] = ...,
        round_increment: int = ...,
        naive_arithmetic_ok: bool = ...,
    ) -> ItemizedDelta: ...
    @overload
    def until(
        self,
        b: Self,
        /,
        *,
        total: Literal[
            "years",
            "months",
            "weeks",
            "days",
            "hours",
            "minutes",
            "seconds",
            "milliseconds",
            "microseconds",
        ],
        naive_arithmetic_ok: bool = ...,
    ) -> float: ...
    @overload
    def until(
        self,
        b: Self,
        /,
        *,
        total: Literal["nanoseconds"],
        naive_arithmetic_ok: bool = ...,
    ) -> int: ...
    @overload
    def until(
        self,
        b: Self,
        /,
        *,
        in_units: Sequence[
            Literal[
                "years",
                "months",
                "weeks",
                "days",
                "hours",
                "minutes",
                "seconds",
                "nanoseconds",
            ]
        ],
        round_mode: Literal[
            "ceil",
            "expand",
            "floor",
            "trunc",
            "half_ceil",
            "half_expand",
            "half_floor",
            "half_trunc",
            "half_even",
        ] = ...,
        round_increment: int = ...,
        naive_arithmetic_ok: bool = ...,
    ) -> ItemizedDelta: ...
    @overload
    def add(
        self,
        *,
        years: int = 0,
        months: int = 0,
        weeks: int = 0,
        days: int = 0,
        hours: float = 0,
        minutes: float = 0,
        seconds: float = 0,
        milliseconds: float = 0,
        microseconds: float = 0,
        nanoseconds: int = 0,
        naive_arithmetic_ok: bool = ...,
    ) -> Self: ...
    @overload
    def add(
        self,
        d: TimeDelta | ItemizedDelta | ItemizedDateDelta,
        /,
        *,
        naive_arithmetic_ok: bool = ...,
    ) -> Self: ...
    @overload
    def subtract(
        self,
        *,
        years: int = 0,
        months: int = 0,
        weeks: int = 0,
        days: int = 0,
        hours: float = 0,
        minutes: float = 0,
        seconds: float = 0,
        milliseconds: float = 0,
        microseconds: float = 0,
        nanoseconds: int = 0,
        naive_arithmetic_ok: bool = ...,
    ) -> Self: ...
    @overload
    def subtract(
        self,
        d: TimeDelta | ItemizedDelta | ItemizedDateDelta,
        /,
        *,
        naive_arithmetic_ok: bool = ...,
    ) -> Self: ...
    def difference(
        self,
        other: Self,
        /,
        *,
        naive_arithmetic_ok: bool = ...,
    ) -> TimeDelta: ...
    def __add__(
        self,
        delta: TimeDelta | ItemizedDelta | ItemizedDateDelta,
        /,
    ) -> Self: ...
    @overload
    def __sub__(
        self,
        other: TimeDelta | ItemizedDelta | ItemizedDateDelta,
        /,
    ) -> Self: ...
    @overload
    def __sub__(self, other: Self, /) -> TimeDelta: ...

@final
class RepeatedTime(ValueError): ...

@final
class SkippedTime(ValueError): ...

@final
class InvalidOffsetError(ValueError): ...

# Why not a subclass of KeyError? Because:
# - It's a better fit. The user doesn't care that it's a lookup, they just care
#   about it being valid or not (ValueError).
# - It can be raised during parsing. Keeping this a ValueError means that
#   the user can catch all parsing exceptions consistently.
@final
class TimeZoneNotFoundError(ValueError): ...

class Weekday(enum.Enum):
    MONDAY = 1
    TUESDAY = 2
    WEDNESDAY = 3
    THURSDAY = 4
    FRIDAY = 5
    SATURDAY = 6
    SUNDAY = 7

MONDAY = Weekday.MONDAY
TUESDAY = Weekday.TUESDAY
WEDNESDAY = Weekday.WEDNESDAY
THURSDAY = Weekday.THURSDAY
FRIDAY = Weekday.FRIDAY
SATURDAY = Weekday.SATURDAY
SUNDAY = Weekday.SUNDAY

def hours(i: float, /) -> TimeDelta: ...
def minutes(i: float, /) -> TimeDelta: ...
def seconds(i: float, /) -> TimeDelta: ...
def milliseconds(i: float, /) -> TimeDelta: ...
def microseconds(i: float, /) -> TimeDelta: ...
def nanoseconds(i: int, /) -> TimeDelta: ...

class TimePatch:
    @overload
    def shift(self, delta: TimeDelta, /) -> None: ...
    @overload
    def shift(
        self,
        *,
        weeks: float = 0,
        days: float = 0,
        hours: float = 0,
        minutes: float = 0,
        seconds: float = 0,
        milliseconds: float = 0,
        microseconds: float = 0,
        nanoseconds: int = 0,
        days_assumed_24h_ok: bool = False,
    ) -> None: ...
    def move_to(
        self, value: Instant | OffsetDateTime | ZonedDateTime, /
    ) -> None: ...

def patch_current_time(
    i: Instant | OffsetDateTime | ZonedDateTime, /, *, keep_ticking: bool
) -> ContextManager[TimePatch]: ...

# Deprecated: use get_tzpath().
TZPATH: tuple[str, ...]

def get_tzpath() -> tuple[str, ...]: ...
def reset_tzpath(
    target: Iterable[str | PathLike[str]] | None = None, /
) -> None: ...
def clear_tzcache(*, only_keys: Iterable[str] | None = None) -> None: ...
def available_timezones() -> set[str]: ...
def reset_system_tz() -> None: ...

class WheneverWarning(UserWarning): ...
class PotentialDstBugWarning(WheneverWarning): ...
class PickleOffsetMismatchWarning(WheneverWarning): ...
class ImplicitDisambiguationWarning(PotentialDstBugWarning): ...
class CalendarUnitCompositionWarning(WheneverWarning): ...
class DaysAssumed24HoursWarning(PotentialDstBugWarning): ...
class StaleOffsetWarning(PotentialDstBugWarning): ...
class NaiveArithmeticWarning(PotentialDstBugWarning): ...
class WheneverDeprecationWarning(WheneverWarning): ...

AnyDelta: TypeAlias = TimeDelta | ItemizedDelta | ItemizedDateDelta
