// Do not manually edit this file.
// It has been autogenerated by scripts/generate_docstrings.py
#![allow(dead_code)]

use std::ffi::CStr;

pub(crate) const PYDANTIC_SCHEMA: &CStr = c"__get_pydantic_core_schema__(source_type, handler)\n--\n\n";
pub(crate) const CALENDARUNITCOMPOSITIONWARNING: &CStr = c"\
Warn when itemized deltas are composed component by component.

Itemized deltas preserve the components they were given:
``1 month`` remains ``1 month`` rather than being normalized to days.
Composing two itemized deltas without a ``relative_to`` reference therefore
performs literal component-wise arithmetic, such as
``ItemizedDateDelta(months=1) + ItemizedDateDelta(months=1)`` becoming
``ItemizedDateDelta(months=2)``.

This is often useful for display and ISO 8601 round-tripping, but it is
not the same as sequentially applying both deltas to a date or datetime.
Calendar units do not compose reliably: for example, adding one month to
January 31 may clamp to the end of February, so adding another month from
there can differ from adding two months to January 31 in one step.
The warning is only emitted when either operand contains a nonzero calendar
unit; exact-only composition does not warn.

Composition is flagged rather than refused (Temporal's ``Duration.add()``
throws without a reference) because a warning serves strict, accepting,
and unaware callers alike: see :ref:`flagged-not-forbidden`.

To preserve calendar-aware semantics, pass ``relative_to=...`` and
``in_units=...`` to :meth:`~whenever.ItemizedDelta.add` or
:meth:`~whenever.ItemizedDateDelta.add`. If component-wise composition is
intentional, pass ``cal_unit_composition_ok=True`` or use Python's
standard warning filters.
";
pub(crate) const DATE: &CStr = c"\
A date without a time component.

>>> d = Date(2021, 1, 2)
Date(\"2021-01-02\")

Can also be constructed from an ISO 8601 string
or a standard library :class:`~datetime.date`:

>>> Date(\"2021-01-02\")
Date(\"2021-01-02\")
>>> from datetime import date
>>> Date(date(2021, 1, 2))
Date(\"2021-01-02\")

Dates support arithmetic with :class:`~whenever.ItemizedDateDelta`:

>>> delta = Date(\"2021-02-28\").since(Date(\"1994-05-15\"), in_units=[\"years\", \"days\"])
ItemizedDateDelta(\"P26y289d\")
>>> Date(\"1994-05-15\").add(delta)
Date(\"2021-02-28\")

Dates can be compared and sorted:

>>> Date(2021, 1, 2) > Date(2021, 1, 1)
True
";
pub(crate) const DAYSASSUMED24HOURSWARNING: &CStr = c"\
Emitted when days are treated as exactly 24 hours, which may be wrong
across a DST transition.

:class:`~whenever.TimeDelta` always represents exact time.
Constructing one with ``days`` or ``weeks`` kwargs converts those units
to nanoseconds using fixed 86400-second days. If you later add this delta
to a :class:`~whenever.ZonedDateTime` on a day where clocks spring forward
or fall back, the local time of the result will be off by the transition
length (usually one hour).

.. rubric:: When it can occur

.. code-block:: python

    from whenever import TimeDelta, ZonedDateTime

    # TimeDelta(days=1) is exactly 86 400 seconds — no DST awareness.
    delta = TimeDelta(days=1)  # DaysAssumed24HoursWarning

    # Adding it to a ZonedDateTime on a spring-forward day gives the
    # wrong local time:
    eve = ZonedDateTime(2025, 3, 30, 12, tz=\"Europe/Amsterdam\")
    eve + delta
    # ZonedDateTime(\"2025-03-31 13:00:00+02:00[Europe/Amsterdam]\")
    # ^^ 13:00, not 12:00 — one hour lost to the DST transition

.. rubric:: How to fix it

Use calendar-based arithmetic directly on the datetime to preserve
local time across transitions:

.. code-block:: python

    eve.add(days=1)
    # ZonedDateTime(\"2025-03-31 12:00:00+02:00[Europe/Amsterdam]\")  ✓

To suppress when exact 24-hour arithmetic is genuinely intended, pass
``days_assumed_24h_ok=True`` (or use Python's standard warning filters):

.. code-block:: python

    TimeDelta(days=1, days_assumed_24h_ok=True)
";
pub(crate) const IMPLICITDISAMBIGUATIONWARNING: &CStr = c"\
Emitted when a repeated or skipped local datetime is resolved without an
explicit disambiguation policy.

Such local datetimes occur around time zone transitions and do not identify
one unambiguous instant. Pass ``disambiguation=`` explicitly to document
whether the compatible, earlier, later, or rejecting behavior is intended.
";
pub(crate) const INSTANT: &CStr = c"\
A moment in time, independent of any time zone or calendar.

This is the right type when you only care about *when* something happened,
not the local date or time. It maps 1:1 to a UNIX timestamp.

>>> from whenever import Instant
>>> py311_release = Instant.from_utc(2022, 10, 24, hour=17)
Instant(\"2022-10-24 17:00:00Z\")
>>> py311_release.add(hours=3).timestamp()
1666641600

Can also be constructed from an ISO 8601 string
or a standard library :class:`~datetime.datetime`:

>>> Instant(\"2022-10-24T17:00:00Z\")
Instant(\"2022-10-24 17:00:00Z\")

Convert to other types for local date/time information:

>>> py311_release.to_tz(\"US/Pacific\")
ZonedDateTime(\"2022-10-24 10:00:00-07:00[US/Pacific]\")

Note
----
Although the debug representation uses UTC, ``Instant`` does *not* have
``.year``, ``.hour``, or other calendar attributes—it is not a UTC datetime.
See the :ref:`FAQ <faq-instant-no-local>`.
";
pub(crate) const INVALIDOFFSETERROR: &CStr = c"\
A string has an invalid offset for the given zone";
pub(crate) const NAIVEARITHMETICWARNING: &CStr = c"\
Emitted when exact-time arithmetic is performed on a
:class:`~whenever.PlainDateTime` without time zone context.

:class:`~whenever.PlainDateTime` carries no time zone information, so it
can't account for DST transitions. When you add or subtract exact time
units (hours, minutes, seconds) or measure the exact difference between
two :class:`~whenever.PlainDateTime` values, the computation treats every
hour as equal. If a time zone transition falls in the interval, the result
may be off by an hour or more.

.. rubric:: When it can occur

.. code-block:: python

    from whenever import PlainDateTime

    # On 2023-10-29, Amsterdam clocks fall back at 3:00 AM.
    # PlainDateTime has no knowledge of this.
    d = PlainDateTime(2023, 10, 29, 1, 30)
    d.add(hours=2)  # NaiveArithmeticWarning
    # PlainDateTime(\"2023-10-29 03:30:00\")
    # ^^ only 1 real hour passed in Amsterdam (clocks went back)

    # Also emitted for exact-unit differences:
    d2 = PlainDateTime(2023, 10, 30, 1, 30)
    d2 - d  # NaiveArithmeticWarning

.. rubric:: How to fix it

Attach a time zone with :meth:`~whenever.PlainDateTime.assume_tz` first,
then perform arithmetic on the resulting :class:`~whenever.ZonedDateTime`:

.. code-block:: python

    d.assume_tz(\"Europe/Amsterdam\").add(hours=2)
    # ZonedDateTime(\"2023-10-29 02:30:00+01:00[Europe/Amsterdam]\")  ✓

To suppress when time zone context doesn't apply (e.g. simulations,
clock times not tied to a real-world time zone, or when you know no
transitions occur in the interval), pass ``naive_arithmetic_ok=True``
(or use Python's standard warning filters):

.. code-block:: python

    d.add(hours=2, naive_arithmetic_ok=True)
";
pub(crate) const OFFSETDATETIME: &CStr = c"\
A datetime with a fixed UTC offset.

Useful for representing a moment in time together with the local
date and time as observed at that offset. The offset is fixed and
does not account for DST transitions.

>>> # Midnight in Salt Lake City
>>> OffsetDateTime(2023, 4, 21, offset=hours(-6))
OffsetDateTime(\"2023-04-21 00:00:00-06:00\")

Can also be constructed from an ISO 8601 string
or a standard library :class:`~datetime.datetime`:

>>> OffsetDateTime(\"2023-04-21T00:00:00-06:00\")
OffsetDateTime(\"2023-04-21 00:00:00-06:00\")

Convert to :class:`~whenever.ZonedDateTime` for DST-aware operations:

>>> dt = OffsetDateTime(2023, 4, 21, offset=hours(-6))
>>> dt.assume_tz(\"US/Mountain\")
ZonedDateTime(\"2023-04-21 00:00:00-06:00[US/Mountain]\")

Important
---------
See the `OffsetDateTime guidance
<https://whenever.readthedocs.io/en/latest/guide/choosing-a-type.html#offset-datetime-guidance>`_
for the information this type preserves and its fixed-offset arithmetic
footgun.
";
pub(crate) const PICKLEOFFSETMISMATCHWARNING: &CStr = c"\
The offset stored in a ZonedDateTime pickle no longer matches the
time zone's current rules.
";
pub(crate) const PLAINDATETIME: &CStr = c"\
A date and time-of-day without any time zone information.

Represents a local time as people observe it, without saying where.
It can't be mixed with exact-time types (e.g. ``Instant``,
``ZonedDateTime``) without explicitly assuming a time zone or offset.

>>> PlainDateTime(2024, 3, 10, 15, 30)
PlainDateTime(\"2024-03-10 15:30:00\")

Can also be constructed from an ISO 8601 string
or a standard library :class:`~datetime.datetime`:

>>> PlainDateTime(\"2024-03-10T15:30:00\")
PlainDateTime(\"2024-03-10 15:30:00\")

Convert to an exact time type by supplying a time zone or offset:

>>> dt = PlainDateTime(2024, 3, 10, 15, 30)
>>> dt.assume_tz(\"Europe/Amsterdam\")
ZonedDateTime(\"2024-03-10 15:30:00+01:00[Europe/Amsterdam]\")
>>> dt.assume_fixed_offset(hours(5))
OffsetDateTime(\"2024-03-10 15:30:00+05:00\")

When to use this type:

- You need to express a date and time as it would appear on a
  local time, independent of time zone.
- You receive a datetime without time zone information and need
  to represent this lack of information in the type system.
- You're working in a context where time zones and DST
  transitions truly don't apply (e.g. a simulation).
";
pub(crate) const POTENTIALDSTBUGWARNING: &CStr = c"\
Base class for warnings about potential DST-related bugs in user code.

Not raised directly. Subclasses cover four distinct scenarios:

- :class:`~whenever.DaysAssumed24HoursWarning` — days treated as exact 24-hour units
- :class:`~whenever.StaleOffsetWarning` — fixed offset may become stale relative to its source time zone
- :class:`~whenever.NaiveArithmeticWarning` — exact-time arithmetic without time zone context
- :class:`~whenever.ImplicitDisambiguationWarning` — resolving a repeated or skipped local time without an explicit policy

Catching or filtering this base class handles all four at once:

.. code-block:: python

    import warnings, whenever
    warnings.filterwarnings(\"error\", category=whenever.PotentialDstBugWarning)
";
pub(crate) const REPEATEDTIME: &CStr = c"\
A local time that is repeated in a time zone, e.g. because of DST.

See :term:`repeated local time`.
";
pub(crate) const SKIPPEDTIME: &CStr = c"\
A local time that is skipped in a time zone, e.g. because of DST.

See :term:`skipped local time`.
";
pub(crate) const STALEOFFSETWARNING: &CStr = c"\
Emitted when an :class:`~whenever.OffsetDateTime` operation may
preserve an offset that is stale relative to its source time zone.

Pass ``stale_offset_ok=True`` to accept this for one call. See
:ref:`offset-datetime-guidance` for the stale-offset footgun, examples,
and remediation.
";
pub(crate) const TIME: &CStr = c"\
Time of day without a date component.

>>> t = Time(12, 30, 0)
Time(\"12:30:00\")

Can also be constructed from an ISO 8601 string:

>>> Time(\"12:30:00\")
Time(\"12:30:00\")

Or a standard library :class:`~datetime.time`:

>>> from datetime import time
>>> Time(time(12, 30, 0))
Time(\"12:30:00\")

Note
----
When constructing from a :class:`~datetime.time`, the ``fold``
attribute and ``tzinfo`` are ignored.

Sub-second precision up to nanoseconds is supported:

>>> Time(12, 30, 0, nanosecond=1)
Time(\"12:30:00.000000001\")

Times can be compared and sorted:

>>> Time(12, 30) > Time(8, 0)
True
";
pub(crate) const TIMEDELTA: &CStr = c"\
A duration consisting of a precise time: hours, minutes, (nano)seconds.
For durations including months or days, use :class:`~ItemizedDelta`,
or :class:`~whenever.ItemizedDateDelta` for date-only durations.

The inputs are normalized, so 90 minutes becomes 1 hour and 30 minutes,
for example.

>>> d = TimeDelta(hours=1, minutes=90)
TimeDelta(\"PT2h30m\")
>>> d.total(\"minutes\")
150.0

Can also be constructed from an ISO 8601 duration string
or a standard library :class:`~datetime.timedelta`:

>>> TimeDelta(\"PT2h30m\")
TimeDelta(\"PT2h30m\")
>>> from datetime import timedelta
>>> TimeDelta(timedelta(hours=2, minutes=30))
TimeDelta(\"PT2h30m\")

``TimeDelta`` can be added to or subtracted from datetime types
to shift them by an exact amount of time:

>>> Instant(\"2022-10-24 00:00Z\") + TimeDelta(hours=3)
Instant(\"2022-10-24 03:00:00Z\")

Note
----
A shorter way to instantiate a timedelta is to use the helper functions
:func:`~whenever.hours`, :func:`~whenever.minutes`, etc.
";
pub(crate) const TIMEZONENOTFOUNDERROR: &CStr = c"\
A time zone with the given ID was not found";
pub(crate) const WHENEVERDEPRECATIONWARNING: &CStr = c"\
Emitted when a deprecated feature of the ``whenever`` library is used.

This is a custom warning class (not a subclass of
:class:`DeprecationWarning`) so that deprecation warnings from this
library are visible by default—unlike standard ``DeprecationWarning``,
which Python silences in application code.
";
pub(crate) const WHENEVERWARNING: &CStr = c"\
Base class for all warnings emitted by the ``whenever`` library.

This can be used with Python's standard warning filters to suppress or
escalate all warnings emitted by ``whenever``:

.. code-block:: python

    import warnings, whenever
    warnings.filterwarnings(\"error\", category=whenever.WheneverWarning)
";
pub(crate) const ZONEDDATETIME: &CStr = c"\
A datetime associated with a time zone from the IANA database.

This is the right type when you need both the exact moment *and*
the local date/time at a specific location. Arithmetic is fully
DST-aware: the offset is always kept in sync with the time zone rules.

>>> ZonedDateTime(\"2024-12-08T11[Europe/Paris]\")
ZonedDateTime(\"2024-12-08 11:00:00+01:00[Europe/Paris]\")
>>> # Explicitly resolve ambiguities during DST transitions
>>> ZonedDateTime(2023, 10, 29, 1, 15, tz=\"Europe/London\", disambiguation=\"earlier\")
ZonedDateTime(\"2023-10-29 01:15:00+01:00[Europe/London]\")
>>> # From a standard library datetime (must have a ZoneInfo tzinfo)
>>> ZonedDateTime(datetime(2020, 8, 15, 23, 12, tzinfo=ZoneInfo(\"Europe/London\")))
ZonedDateTime(\"2020-08-15 23:12:00+01:00[Europe/London]\")

Convert to other types to discard time zone information:

>>> d = ZonedDateTime(2024, 7, 1, 12, tz=\"Europe/Amsterdam\")
>>> d.to_instant()
Instant(\"2024-07-01 10:00:00Z\")
>>> d.to_plain()
PlainDateTime(\"2024-07-01 12:00:00\")

Important
---------
To use this type properly, read more about
`resolving local times in time zones
<https://whenever.readthedocs.io/en/latest/guide/resolving-local-times.html>`_.
For ISO inputs containing both an offset and time zone ID, see the
`offset-mismatch flow
<https://whenever.readthedocs.io/en/latest/guide/resolving-local-times.html#offset-mismatch>`_.
";
pub(crate) const HOURS: &CStr = c"\
Create a :class:`~TimeDelta` with the given number of hours.
``hours(1) == TimeDelta(hours=1)``
";
pub(crate) const MICROSECONDS: &CStr = c"\
Create a :class:`TimeDelta` with the given number of microseconds.
``microseconds(1) == TimeDelta(microseconds=1)``
";
pub(crate) const MILLISECONDS: &CStr = c"\
Create a :class:`TimeDelta` with the given number of milliseconds.
``milliseconds(1) == TimeDelta(milliseconds=1)``
";
pub(crate) const MINUTES: &CStr = c"\
Create a :class:`TimeDelta` with the given number of minutes.
``minutes(1) == TimeDelta(minutes=1)``
";
pub(crate) const NANOSECONDS: &CStr = c"\
Create a :class:`TimeDelta` with the given number of nanoseconds.
``nanoseconds(1) == TimeDelta(nanoseconds=1)``
";
pub(crate) const RESET_SYSTEM_TZ: &CStr = c"\
Resets the cached system time zone to the currently set system time zone.

>>> os.environ[\"TZ\"] = \"America/New_York\"
>>> reset_system_tz()  # system tz is now New York
>>> os.environ[\"TZ\"] = \"Europe/London\"
>>> ZonedDateTime.now(SYSTEM_TZ)  # still uses cached New York tz
ZonedDateTime(\"2025-06-18 15:11:08-04:00[America/New_York]\")
>>> reset_system_tz()  # system tz is now London
>>> ZonedDateTime.now(SYSTEM_TZ)
ZonedDateTime(\"2025-06-18 20:11:08+01:00[Europe/London]\")
";
pub(crate) const SECONDS: &CStr = c"\
Create a :class:`TimeDelta` with the given number of seconds.
``seconds(1) == TimeDelta(seconds=1)``
";
pub(crate) const DATE_ADD: &CStr = c"\
add($self, delta=..., /, *, years=0, months=0, weeks=0, days=0)
--

Add a components to a date.

See :ref:`the docs on arithmetic <arithmetic>` for more information.

>>> d = Date(2021, 1, 2)
>>> d.add(years=1, months=2, days=3)
Date(\"2022-03-05\")
>>> Date(2020, 2, 29).add(years=1)
Date(\"2021-02-28\")
";
pub(crate) const DATE_AT: &CStr = c"\
Combine a date with a time to create a datetime

>>> d = Date(2021, 1, 2)
>>> d.at(Time(12, 30))
PlainDateTime(\"2021-01-02 12:30:00\")

You can use methods like :meth:`~PlainDateTime.assume_utc`
or :meth:`~PlainDateTime.assume_tz` to find the corresponding exact time.
";
pub(crate) const DATE_DAY: &CStr = c"\
The day component of the date

>>> Date(2021, 1, 2).day
2
";
pub(crate) const DATE_DAY_OF_WEEK: &CStr = c"\
The day of the week

>>> Date(2021, 1, 2).day_of_week()
Weekday.SATURDAY
>>> Weekday.SATURDAY.value
6  # the ISO value
";
pub(crate) const DATE_DAY_OF_YEAR: &CStr = c"\
Ordinal day in the year (1--366)

>>> Date(2021, 1, 2).day_of_year()
2
>>> Date(2021, 12, 31).day_of_year()
365
";
pub(crate) const DATE_DAYS_IN_MONTH: &CStr = c"\
Number of days in the current month (28--31)

>>> Date(2024, 2, 1).days_in_month()
29
>>> Date(2023, 2, 1).days_in_month()
28
";
pub(crate) const DATE_DAYS_IN_YEAR: &CStr = c"\
Number of days in the current year (365 or 366)

>>> Date(2024, 1, 1).days_in_year()
366
>>> Date(2023, 1, 1).days_in_year()
365
";
pub(crate) const DATE_END_OF: &CStr = c"\
The end of the given calendar unit

>>> Date(2024, 8, 15).end_of(\"year\")
Date(\"2024-12-31\")
>>> Date(2024, 8, 15).end_of(\"month\")
Date(\"2024-08-31\")
>>> Date(2024, 8, 15).end_of(\"week_mon\")
Date(\"2024-08-18\")

See also :meth:`start_of`
";
pub(crate) const DATE_FORMAT: &CStr = c"\
Format as a custom pattern string.

See :ref:`pattern-format` for details.

>>> Date(2024, 3, 15).format(\"YYYY/MM/DD\")
'2024/03/15'
>>> Date(2024, 3, 15).format(\"DD MMM YYYY\")
'15 Mar 2024'
";
pub(crate) const DATE_FORMAT_ISO: &CStr = c"\
format_iso($self, *, basic=False)
--

Format as the ISO 8601 date format.

Inverse of :meth:`parse_iso`.

>>> Date(2021, 1, 2).format_iso()
'2021-01-02'
>>> Date(1992, 9, 4).format_iso(basic=True)
'19920904'
";
pub(crate) const DATE_IN_LEAP_YEAR: &CStr = c"\
Whether this date's year is a leap year

>>> Date(2024, 1, 1).in_leap_year()
True
>>> Date(2023, 1, 1).in_leap_year()
False
";
pub(crate) const DATE_ISO_WEEK_DATE: &CStr = c"\
The ISO week date for this date

>>> Date(2024, 12, 30).iso_week_date()
IsoWeekDate(\"2025-W01-1\")
";
pub(crate) const DATE_MONTH: &CStr = c"\
The month component of the date

>>> Date(2021, 1, 2).month
1
";
pub(crate) const DATE_MONTH_DAY: &CStr = c"\
The month and day (without a year component)

>>> Date(2021, 1, 2).month_day()
MonthDay(\"--01-02\")
";
pub(crate) const DATE_NEXT_DAY: &CStr = c"\
The date immediately following

>>> Date(2021, 1, 2).next_day()
Date(\"2021-01-03\")
";
pub(crate) const DATE_NTH_WEEKDAY: &CStr = c"\
nth_weekday($self, n, weekday, /)
--

The n-th occurrence of a weekday from this date (exclusive).

Negative ``n`` searches backward.
``n=0`` raises :class:`ValueError`, as does a result outside
``Date.MIN``..``Date.MAX``.

>>> Date(2024, 8, 1).nth_weekday(1, Weekday.FRIDAY)
Date(\"2024-08-02\")
>>> Date(2024, 8, 1).nth_weekday(-1, Weekday.WEDNESDAY)
Date(\"2024-07-31\")
";
pub(crate) const DATE_NTH_WEEKDAY_OF_MONTH: &CStr = c"\
nth_weekday_of_month($self, n, weekday, /)
--

The n-th occurrence of a weekday in this date's month.

Negative ``n`` counts from the end.
``n=0`` raises :class:`ValueError`, as does an occurrence the month
does not have, such as a fifth Monday in a month with four.

>>> Date(2024, 8, 1).nth_weekday_of_month(2, Weekday.FRIDAY)
Date(\"2024-08-09\")
>>> Date(2024, 8, 1).nth_weekday_of_month(-1, Weekday.FRIDAY)
Date(\"2024-08-30\")
";
pub(crate) const DATE_PARSE: &CStr = c"\
parse(s, /, *, pattern=...)
--

Parse a date from a custom pattern string.

See :ref:`pattern-format` for details.

>>> Date.parse(\"2024/03/15\", pattern=\"YYYY/MM/DD\")
Date(\"2024-03-15\")
>>> Date.parse(\"15 Mar 2024\", pattern=\"DD MMM YYYY\")
Date(\"2024-03-15\")
";
pub(crate) const DATE_PARSE_ISO: &CStr = c"\
Parse a date from an ISO8601 string

The following formats are accepted:
- ``YYYY-MM-DD`` (\"extended\" format)
- ``YYYYMMDD`` (\"basic\" format)

Inverse of :meth:`format_iso`

>>> Date.parse_iso(\"2021-01-02\")
Date(\"2021-01-02\")
";
pub(crate) const DATE_PREV_DAY: &CStr = c"\
The date immediately preceding

>>> Date(2021, 1, 2).prev_day()
Date(\"2021-01-01\")
";
pub(crate) const DATE_REPLACE: &CStr = c"\
replace($self, /, *, year=..., month=..., day=...)
--

Create a new instance with the given fields replaced

A result that is not a valid date raises :class:`ValueError`.

>>> d = Date(2021, 1, 2)
>>> d.replace(day=4)
Date(\"2021-01-04\")
";
pub(crate) const DATE_SINCE: &CStr = c"\
since($self, b, /, *, total=..., in_units=..., round_mode=..., round_increment=...)
--

Calculate the difference between this date and another date.
The difference is calculated in terms of the chosen calendar unit
or units.

>>> d = Date(2023, 4, 15)
>>> d.since(Date(\"2020-01-01\"), in_units=[\"years\", \"months\"])
ItemizedDateDelta(\"P3y3m\")

>>> d.since(Date(\"2020-01-01\"), total=\"weeks\")
170.0

Parameters
----------
other
    The date to calculate the difference since.
total
    If specified, the difference is returned as a float in terms
    of this single unit. Cannot be combined with ``in_units``.

    The fractional part is based on the number of days in the
    surrounding calendar period — not a fixed conversion factor.
    For example, 6 months from January 1 spans 181 days of a
    365-day year, giving approximately 0.496 years, not 0.5.
in_units
    If specified, the difference is calculated in terms of these units,
    in decreasing order of size. Cannot be combined with ``total``.
round_mode
    The rounding mode to apply to the smallest specified unit.
    Only valid with ``in_units``.
round_increment
    The increment to round to for the smallest specified unit.
    Only valid with ``in_units``.

Returns
-------
ItemizedDateDelta | float
    If ``in_units`` is specified, the difference is returned
    as an :class:`ItemizedDateDelta`,
    If ``total`` is specified, as a float number of the specified unit.

";
pub(crate) const DATE_START_OF: &CStr = c"\
The start of the given calendar unit

>>> Date(2024, 8, 15).start_of(\"year\")
Date(\"2024-01-01\")
>>> Date(2024, 8, 15).start_of(\"month\")
Date(\"2024-08-01\")
>>> Date(2024, 8, 15).start_of(\"week_mon\")
Date(\"2024-08-12\")
";
pub(crate) const DATE_SUBTRACT: &CStr = c"\
subtract($self, delta=..., /, *, years=0, months=0, weeks=0, days=0)
--

Subtract components from a date.

See :ref:`the docs on arithmetic <arithmetic>` for more information.

>>> d = Date(2021, 1, 2)
>>> d.subtract(years=1, months=2, days=3)
Date(\"2019-10-30\")
>>> Date(2021, 3, 1).subtract(years=1)
Date(\"2020-03-01\")
";
pub(crate) const DATE_TO_STDLIB: &CStr = c"\
Convert to a standard library :class:`~datetime.date`";
pub(crate) const DATE_TODAY: &CStr = c"\
Get the current date in the given time zone.
Pass ``SYSTEM_TZ`` for the system time zone.
";
pub(crate) const DATE_TODAY_IN_SYSTEM_TZ: &CStr = c"\
Get the current date in the system time zone.

.. deprecated:: 0.11
   Use ``Date.today(SYSTEM_TZ)`` instead.

Equivalent to ``today(SYSTEM_TZ)``.

>>> Date.today_in_system_tz()
Date(\"2021-01-02\")
";
pub(crate) const DATE_UNTIL: &CStr = c"\
until($self, b, /, *, total=..., in_units=..., round_mode=..., round_increment=...)
--

Companion to :meth:`since` that calculates the difference until another date.
See :meth:`since` for more information.
";
pub(crate) const DATE_YEAR: &CStr = c"\
The year component of the date

>>> Date(2021, 1, 2).year
2021
";
pub(crate) const DATE_YEAR_MONTH: &CStr = c"\
The year and month (without a day component)

>>> Date(2021, 1, 2).year_month()
YearMonth(\"2021-01\")
";
pub(crate) const INSTANT_ADD: &CStr = c"\
add($self, delta=..., /, *, weeks=0, days=0, hours=0, minutes=0, seconds=0, milliseconds=0, microseconds=0, nanoseconds=0, days_assumed_24h_ok=False)
--

Add a time amount to this instant.

See the `docs on arithmetic <https://whenever.rtfd.io/en/latest/guide/arithmetic.html>`__ for more information.
";
pub(crate) const INSTANT_FORMAT: &CStr = c"\
Format as a custom pattern string.

Instant formats as UTC; See :ref:`pattern-format` for details.

>>> Instant.from_utc(2024, 3, 15, 14, 30).format(\"YYYY-MM-DD HH:mm:ssXXX\")
'2024-03-15 14:30:00Z'
";
pub(crate) const INSTANT_FORMAT_ISO: &CStr = c"\
format_iso($self, *, unit='auto', basic=False, sep='T')
--

Convert to the ISO 8601 string representation.

The inverse of the ``parse_iso()`` method.
";
pub(crate) const INSTANT_FORMAT_RFC2822: &CStr = c"\
Format as an RFC 2822 string in the fixed UTC/GMT subset.

RFC 2822 has whole-second precision, so nanoseconds are discarded.

>>> Instant.from_utc(2020, 8, 8, hour=23, minute=12).format_rfc2822()
\"Sat, 08 Aug 2020 23:12:00 GMT\"

Note
----
This is also the IMF-fixdate representation used to generate HTTP dates
under the stricter RFC 9110 standard.

";
pub(crate) const INSTANT_FROM_TIMESTAMP: &CStr = c"\
from_timestamp(value, /, *, unit='second')
--

Create an Instant from a UNIX timestamp in the requested unit.

The inverse of the ``timestamp()`` method.

Seconds accept integers and floats, which are floored to whole
nanoseconds; milliseconds, microseconds, and nanoseconds require
integers. A value outside ``Instant.MIN..MAX`` raises ``ValueError``.
";
pub(crate) const INSTANT_FROM_TIMESTAMP_MILLIS: &CStr = c"\
Create an Instant from a UNIX timestamp (in milliseconds).

.. deprecated:: 0.11
   Use ``from_timestamp(..., unit=\"millisecond\")`` instead.

The inverse of the ``timestamp_millis()`` method.
";
pub(crate) const INSTANT_FROM_TIMESTAMP_NANOS: &CStr = c"\
Create an Instant from a UNIX timestamp (in nanoseconds).

.. deprecated:: 0.11
   Use ``from_timestamp(..., unit=\"nanosecond\")`` instead.

The inverse of the ``timestamp_nanos()`` method.
";
pub(crate) const INSTANT_FROM_UTC: &CStr = c"\
from_utc(year, month, day, hour=0, minute=0, second=0, *, nanosecond=0)
--

Create an Instant from a date and time-of-day in UTC.
This is the field constructor of ``Instant``; see the
:ref:`FAQ <faq-instant-no-local>` for why ``Instant(...)`` takes no fields.

>>> Instant.from_utc(2022, 10, 24, hour=17)
Instant(\"2022-10-24 17:00:00Z\")
";
pub(crate) const INSTANT_NOW: &CStr = c"\
Create an Instant from the current time.

>>> Instant.now()
Instant(\"2024-06-15 12:34:56.789123456Z\")
";
pub(crate) const INSTANT_PARSE: &CStr = c"\
parse(s, /, *, pattern=...)
--

Parse an instant from a custom pattern string.

The pattern **must** include an offset field (``x``/``X``)
to unambiguously identify the instant.
See :ref:`pattern-format` for details.

.. tip::

    If your input string doesn't include an offset, parse it with
    :meth:`PlainDateTime.parse` first, then convert using
    :meth:`~PlainDateTime.assume_utc` or
    :meth:`~PlainDateTime.assume_tz`.

>>> Instant.parse(\"2024-03-15 14:30Z\", pattern=\"YYYY-MM-DD HH:mmXXX\")
Instant(\"2024-03-15 14:30:00Z\")
>>> Instant.parse(\"2024-03-15 14:30+05:30\", pattern=\"YYYY-MM-DD HH:mmxxx\")
Instant(\"2024-03-15 09:00:00Z\")
";
pub(crate) const INSTANT_PARSE_ISO: &CStr = c"\
Parse an ISO 8601 string. Supports basic and extended formats,
but not week dates or ordinal dates.

See the `docs on ISO8601 support <https://whenever.rtfd.io/en/latest/reference/iso8601.html>`__ for more information.

The inverse of the ``format_iso()`` method.
";
pub(crate) const INSTANT_PARSE_RFC2822: &CStr = c"\
Parse a UTC datetime in RFC 2822 format.

>>> Instant.parse_rfc2822(\"Sat, 15 Aug 2020 23:12:00 GMT\")
Instant(\"2020-08-15 23:12:00Z\")

>>> # also valid:
>>> Instant.parse_rfc2822(\"Sat, 15 Aug 2020 23:12:00 +0000\")
>>> Instant.parse_rfc2822(\"Sat, 15 Aug 2020 23:12:00 +0800\")
>>> Instant.parse_rfc2822(\"Sat, 15 Aug 2020 23:12:00 -0000\")
>>> Instant.parse_rfc2822(\"Sat, 15 Aug 2020 23:12:00 UT\")
>>> Instant.parse_rfc2822(\"Sat, 15 Aug 2020 23:12:00 MST\")

Note
----
- Although technically part of the RFC 2822 standard,
  comments within folding whitespace are not supported.
";
pub(crate) const INSTANT_ROUND: &CStr = c"\
round($self, unit='second', /, *, increment=1, mode='half_even')
--

Round the instant to the specified unit and increment,
or to a multiple of a :class:`TimeDelta`.
Various rounding modes are available.

>>> Instant.from_utc(2020, 1, 1, 12, 39, 59).round(\"minute\", increment=15)
Instant(\"2020-01-01 12:45:00Z\")
>>> Instant.from_utc(2020, 1, 1, 8, 9, 13).round(\"second\", increment=5, mode=\"floor\")
Instant(\"2020-01-01 08:09:10Z\")
>>> Instant.from_utc(2020, 1, 1, 12, 39, 59).round(TimeDelta(minutes=15))
Instant(\"2020-01-01 12:45:00Z\")
";
pub(crate) const INSTANT_SUBTRACT: &CStr = c"\
subtract($self, delta=..., /, *, weeks=0, days=0, hours=0, minutes=0, seconds=0, milliseconds=0, microseconds=0, nanoseconds=0, days_assumed_24h_ok=False)
--

Subtract a time amount from this instant.

See the `docs on arithmetic <https://whenever.rtfd.io/en/latest/guide/arithmetic.html>`__ for more information.
";
pub(crate) const OFFSETDATETIME_ADD: &CStr = c"\
add($self, delta=..., /, *, years=0, months=0, weeks=0, days=0, hours=0, minutes=0, seconds=0, milliseconds=0, microseconds=0, nanoseconds=0, stale_offset_ok=False)
--

Add a time amount to this datetime.

Warning
-------
See the `OffsetDateTime guidance
<https://whenever.readthedocs.io/en/latest/guide/choosing-a-type.html#offset-datetime-guidance>`_
for the fixed-offset arithmetic footgun. Pass
``stale_offset_ok=True`` when preserving the offset is intentional.
";
pub(crate) const OFFSETDATETIME_ASSUME_TZ: &CStr = c"\
assume_tz($self, tz, /, *, offset_mismatch='raise', disambiguation=...)
--

Associate this offset datetime with a time zone, returning a ZonedDateTime.

This is the inverse of :meth:`ZonedDateTime.to_fixed_offset`.

See the `timezone-resolution guide
<https://whenever.readthedocs.io/en/latest/guide/resolving-local-times.html#offset-mismatch>`_
for how ``offset_mismatch`` interacts with ``disambiguation``.
";
pub(crate) const OFFSETDATETIME_END_OF: &CStr = c"\
end_of($self, unit, /, *, stale_offset_ok=...)
--

The end of the given unit

>>> OffsetDateTime(2024, 8, 15, 14, 30, offset=hours(5)).end_of(\"day\")
OffsetDateTime(\"2024-08-15 23:59:59.999999999+05:00\")

See also :meth:`start_of`
";
pub(crate) const OFFSETDATETIME_FORMAT: &CStr = c"\
Format as a custom pattern string.

See :ref:`pattern-format` for details.

>>> OffsetDateTime(2024, 3, 15, 14, 30, offset=hours(2)).format(
...     \"YYYY-MM-DD HH:mmxxx\"
... )
'2024-03-15 14:30+02:00'
";
pub(crate) const OFFSETDATETIME_FORMAT_ISO: &CStr = c"\
format_iso($self, *, unit='auto', basic=False, sep='T')
--

Convert to the popular ISO format ``YYYY-MM-DDTHH:MM:SS±HH:MM``

The inverse of the ``parse_iso()`` method.
";
pub(crate) const OFFSETDATETIME_FORMAT_RFC2822: &CStr = c"\
Format as an RFC 2822 string.

RFC 2822 has whole-second datetimes and minute-precision offsets.
Nanoseconds and offset seconds are discarded.

>>> OffsetDateTime(2020, 8, 15, 23, 12, offset=hours(2)).format_rfc2822()
\"Sat, 15 Aug 2020 23:12:00 +0200\"
";
pub(crate) const OFFSETDATETIME_FROM_TIMESTAMP: &CStr = c"\
from_timestamp(value, /, *, offset, stale_offset_ok=...)
--

Create an instance from a UNIX timestamp (in seconds).

.. deprecated:: 0.11
   Create an :class:`Instant` and call ``to_fixed_offset()`` instead.

The inverse of the ``timestamp()`` method.

Warning
-------
Converting a UNIX timestamp to ``OffsetDateTime`` with a fixed UTC offset
is correct for that offset, but the offset may be stale for the region you
intend at that timestamp: a fixed offset contains no DST or other time zone
rules. Use
``ZonedDateTime.from_timestamp(ts, tz='<tz>')`` if you know the time zone,
or ``Instant.from_timestamp()`` for exact time independent of any time zone.
Pass ``stale_offset_ok=True`` to suppress.
";
pub(crate) const OFFSETDATETIME_FROM_TIMESTAMP_MILLIS: &CStr = c"\
from_timestamp_millis(value, /, *, offset, stale_offset_ok=...)
--

Create an instance from a UNIX timestamp (in milliseconds).

.. deprecated:: 0.11
   Use ``Instant.from_timestamp(..., unit=\"millisecond\").to_fixed_offset()``.

The inverse of the ``timestamp_millis()`` method.

See :meth:`from_timestamp` for more information.
";
pub(crate) const OFFSETDATETIME_FROM_TIMESTAMP_NANOS: &CStr = c"\
from_timestamp_nanos(value, /, *, offset, stale_offset_ok=...)
--

Create an instance from a UNIX timestamp (in nanoseconds).

.. deprecated:: 0.11
   Use ``Instant.from_timestamp(..., unit=\"nanosecond\").to_fixed_offset()``.

The inverse of the ``timestamp_nanos()`` method.

See :meth:`from_timestamp` for more information.
";
pub(crate) const OFFSETDATETIME_NOW: &CStr = c"\
now(offset, /, *, stale_offset_ok=...)
--

Create an instance from the current time at the given offset.

>>> OffsetDateTime.now(hours(2), stale_offset_ok=True)
OffsetDateTime(\"2024-03-09 23:00:00+02:00\")

Warning
-------
A fixed offset may be stale relative to the region you intend. See the
`OffsetDateTime guidance
<https://whenever.readthedocs.io/en/latest/guide/choosing-a-type.html#offset-datetime-guidance>`_.
Pass ``stale_offset_ok=True`` when the fixed offset is intentional.
";
pub(crate) const OFFSETDATETIME_PARSE: &CStr = c"\
parse(s, /, *, pattern=...)
--

Parse an offset datetime from a custom pattern string.

The pattern **must** include an offset field (``x``/``X``).
See :ref:`pattern-format` for details.

.. tip::

    If your input string doesn't include an offset, parse it with
    :meth:`PlainDateTime.parse` first, then convert using
    :meth:`~PlainDateTime.assume_fixed_offset` or
    :meth:`~PlainDateTime.assume_tz`.

>>> OffsetDateTime.parse(\"2024-03-15 14:30+02:00\", pattern=\"YYYY-MM-DD HH:mmxxx\")
OffsetDateTime(\"2024-03-15 14:30:00+02:00\")
";
pub(crate) const OFFSETDATETIME_PARSE_ISO: &CStr = c"\
Parse an ISO 8601 string with a UTC offset.

Supports ``YYYY-MM-DDTHH:MM:SS±HH:MM`` and variants
(see the `ISO 8601 docs <https://whenever.rtfd.io/en/latest/reference/iso8601.html>`__
for full details).

The inverse of the ``format_iso()`` method.

>>> OffsetDateTime.parse_iso(\"2020-08-15T23:12:00+02:00\")
OffsetDateTime(\"2020-08-15 23:12:00+02:00\")

Note
----
``Z`` is accepted as an offset and treated as ``+00:00``.
Strictly speaking, ``Z`` means \"UTC\" (i.e. no fixed offset),
but in practice it is almost universally used as a synonym for ``+00:00``.
";
pub(crate) const OFFSETDATETIME_PARSE_RFC2822: &CStr = c"\
Parse an offset datetime in RFC 2822 format.

>>> OffsetDateTime.parse_rfc2822(\"Sat, 15 Aug 2020 23:12:00 +0200\")
OffsetDateTime(\"2020-08-15 23:12:00+02:00\")
>>> # also valid:
>>> OffsetDateTime.parse_rfc2822(\"Sat, 15 Aug 2020 23:12:00 UT\")
>>> OffsetDateTime.parse_rfc2822(\"Sat, 15 Aug 2020 23:12:00 GMT\")
>>> OffsetDateTime.parse_rfc2822(\"Sat, 15 Aug 2020 23:12:00 MST\")

Note
----
- Strictly speaking, an offset of ``-0000`` means that the offset
  is \"unknown\". Here, we treat it the same as +0000.
- Although technically part of the RFC 2822 standard,
  comments within folding whitespace are not supported.
";
pub(crate) const OFFSETDATETIME_REPLACE: &CStr = c"\
replace($self, /, *, year=..., month=..., day=..., hour=..., minute=..., second=..., nanosecond=..., offset=..., stale_offset_ok=...)
--

Create a new instance with the given fields replaced

A stated ``offset=`` keeps the local fields and moves the instant,
the reverse of :meth:`to_fixed_offset`, and is silent. Any other
replacement carries the current offset, which may be stale relative
to its source time zone, and emits :class:`StaleOffsetWarning`
unless ``stale_offset_ok=True``. See
:ref:`offset-datetime-guidance`.

>>> d = OffsetDateTime(2024, 3, 9, 12, offset=hours(-7))
>>> d.replace(offset=hours(-6))
OffsetDateTime(\"2024-03-09 12:00:00-06:00\")
>>> d.replace(day=10, stale_offset_ok=True)
OffsetDateTime(\"2024-03-10 12:00:00-07:00\")
";
pub(crate) const OFFSETDATETIME_REPLACE_DATE: &CStr = c"\
replace_date($self, date, /, *, stale_offset_ok=...)
--

Create a new instance with the date replaced

See :meth:`replace` for more information. The offset is always
carried, so this warns unless ``stale_offset_ok=True``.

>>> d = OffsetDateTime(2024, 3, 9, 12, offset=hours(-7))
>>> d.replace_date(Date(2024, 12, 25), stale_offset_ok=True)
OffsetDateTime(\"2024-12-25 12:00:00-07:00\")
";
pub(crate) const OFFSETDATETIME_REPLACE_TIME: &CStr = c"\
replace_time($self, time, /, *, stale_offset_ok=...)
--

Create a new instance with the time replaced

See :meth:`replace` for more information. The offset is always
carried, so this warns unless ``stale_offset_ok=True``.

>>> d = OffsetDateTime(2024, 3, 9, 12, offset=hours(-7))
>>> d.replace_time(Time(8, 30), stale_offset_ok=True)
OffsetDateTime(\"2024-03-09 08:30:00-07:00\")
";
pub(crate) const OFFSETDATETIME_ROUND: &CStr = c"\
round($self, unit='second', /, *, increment=1, mode='half_even', stale_offset_ok=...)
--

Round the datetime to the specified unit and increment,
or to a multiple of a :class:`TimeDelta`.
Different rounding modes are available.

>>> d = OffsetDateTime(2020, 8, 15, 23, 24, 18, offset=hours(4))
>>> d.round(\"day\")
OffsetDateTime(\"2020-08-16 00:00:00+04:00\")
>>> d.round(\"minute\", increment=15, mode=\"floor\")
OffsetDateTime(\"2020-08-15 23:15:00+04:00\")

Warning
-------
The preserved offset may be stale relative to its source time zone. See
the `OffsetDateTime guidance
<https://whenever.readthedocs.io/en/latest/guide/choosing-a-type.html#offset-datetime-guidance>`_.
Pass ``stale_offset_ok=True`` when preserving it is intentional.
";
pub(crate) const OFFSETDATETIME_SINCE: &CStr = c"\
since($self, b, /, *, total=..., in_units=..., round_mode=..., round_increment=...)
--

Calculate the duration since another OffsetDateTime,
in terms of the specified units.

>>> d1 = OffsetDateTime(2020, 8, 15, 23, 12, offset=hours(2))
>>> d2 = OffsetDateTime(2020, 8, 14, 22, offset=hours(2))
>>> d1.since(d2, in_units=[\"hours\", \"minutes\"],
...          round_increment=15,
...          round_mode=\"ceil\")
ItemizedDelta(\"PT25h15m\")

When calculating calendar units (years, months, weeks, days),
both datetimes must have the same offset.
";
pub(crate) const OFFSETDATETIME_START_OF: &CStr = c"\
start_of($self, unit, /, *, stale_offset_ok=...)
--

The start of the given unit

>>> OffsetDateTime(2024, 8, 15, 14, 30, offset=hours(5)).start_of(\"day\")
OffsetDateTime(\"2024-08-15 00:00:00+05:00\")

Warning
-------
The preserved offset may be stale relative to its source time zone. See
the `OffsetDateTime guidance
<https://whenever.readthedocs.io/en/latest/guide/choosing-a-type.html#offset-datetime-guidance>`_.
Pass ``stale_offset_ok=True`` when preserving it is intentional.
";
pub(crate) const OFFSETDATETIME_SUBTRACT: &CStr = c"\
subtract($self, delta=..., /, *, years=0, months=0, weeks=0, days=0, hours=0, minutes=0, seconds=0, milliseconds=0, microseconds=0, nanoseconds=0, stale_offset_ok=False)
--

Subtract a time amount from this datetime.

See :meth:`add` for more information.
";
pub(crate) const OFFSETDATETIME_UNTIL: &CStr = c"\
until($self, b, /, *, total=..., in_units=..., round_mode=..., round_increment=...)
--

Inverse of the ``since()`` method. See :meth:`since` for more information.";
pub(crate) const PLAINDATETIME_ADD: &CStr = c"\
add($self, delta=..., /, *, years=0, months=0, weeks=0, days=0, hours=0, minutes=0, seconds=0, milliseconds=0, microseconds=0, nanoseconds=0, naive_arithmetic_ok=False)
--

Add a time amount to this datetime.

Warning
-------
Adding **exact time units** (e.g. hours, seconds) to a ``PlainDateTime``
does not account for time zone transitions that may occur in the interval.
Use ``.assume_tz('<tz>') + delta`` if you know the time zone.
Pass ``naive_arithmetic_ok=True`` to suppress;
Python's standard warning filters also apply.
";
pub(crate) const PLAINDATETIME_ASSUME_FIXED_OFFSET: &CStr = c"\
Assume the datetime has the given offset, creating an ``OffsetDateTime``.

>>> PlainDateTime(2020, 8, 15, 23, 12).assume_fixed_offset(hours(2))
OffsetDateTime(\"2020-08-15 23:12:00+02:00\")
";
pub(crate) const PLAINDATETIME_ASSUME_SYSTEM_TZ: &CStr = c"\
assume_system_tz($self, *, disambiguation=...)
--

Assume the datetime is in the system time zone,
creating a ``ZonedDateTime``.

.. deprecated:: 0.11
   Use ``assume_tz(SYSTEM_TZ)`` instead.

Note
----
The local time may be ambiguous in the system time zone
(e.g. during a DST transition). You can explicitly
specify how to handle such a situation using ``disambiguation``.
See `the documentation
<https://whenever.readthedocs.io/en/latest/guide/resolving-local-times.html>`__
for more information.

>>> d = PlainDateTime(2020, 8, 15, 23, 12)
>>> # assuming system time zone is America/New_York
>>> d.assume_tz(SYSTEM_TZ, disambiguation=\"raise\")
ZonedDateTime(\"2020-08-15 23:12:00-04:00[America/New_York]\")
";
pub(crate) const PLAINDATETIME_ASSUME_TZ: &CStr = c"\
assume_tz($self, tz, /, *, disambiguation=...)
--

Assume the datetime is in the given time zone,
creating a ``ZonedDateTime``.

Note
----
The local time may be ambiguous in the given time zone
(e.g. during a DST transition). You can explicitly
specify how to handle such a situation using the ``disambiguation`` argument.
See `the documentation
<https://whenever.readthedocs.io/en/latest/guide/resolving-local-times.html>`__
for more information.

>>> d = PlainDateTime(2020, 8, 15, 23, 12)
>>> d.assume_tz(\"Europe/Amsterdam\", disambiguation=\"raise\")
ZonedDateTime(\"2020-08-15 23:12:00+02:00[Europe/Amsterdam]\")
";
pub(crate) const PLAINDATETIME_ASSUME_UTC: &CStr = c"\
Assume the datetime is in UTC, creating an ``Instant``.

>>> PlainDateTime(2020, 8, 15, 23, 12).assume_utc()
Instant(\"2020-08-15 23:12:00Z\")
";
pub(crate) const PLAINDATETIME_DIFFERENCE: &CStr = c"\
difference($self, other, /, *, naive_arithmetic_ok=...)
--

Calculate the exact time difference between two plain datetimes.

This method returns the exact elapsed :class:`TimeDelta` between two
``PlainDateTime`` values. Equivalent to the subtraction operator (``-``),
but allows suppressing the :class:`NaiveArithmeticWarning`
via the ``naive_arithmetic_ok`` parameter.

Use :meth:`since` or :meth:`until` for more advanced options such as
calendar units, unit decomposition, and rounding.

Warning
-------
Calculating the difference between two ``PlainDateTime`` values does
not account for time zone transitions. Use :meth:`assume_tz` to convert
to a ``ZonedDateTime`` first for accurate results.
";
pub(crate) const PLAINDATETIME_END_OF: &CStr = c"\
The end of the given unit

>>> PlainDateTime(2024, 8, 15, 14, 30, 45).end_of(\"day\")
PlainDateTime(\"2024-08-15 23:59:59.999999999\")
>>> PlainDateTime(2024, 8, 15, 14, 30, 45).end_of(\"hour\")
PlainDateTime(\"2024-08-15 14:59:59.999999999\")

See also :meth:`start_of`
";
pub(crate) const PLAINDATETIME_FORMAT: &CStr = c"\
Format as a custom pattern string.

Also available via ``f\"{dt:YYYY-MM-DD HH:mm}\"`` (Python's ``__format__``
protocol), where an empty spec falls back to :meth:`__str__`.

See :ref:`pattern-format` for details.

>>> PlainDateTime(2024, 3, 15, 14, 30).format(\"YYYY-MM-DD HH:mm\")
'2024-03-15 14:30'
";
pub(crate) const PLAINDATETIME_FORMAT_ISO: &CStr = c"\
format_iso($self, *, unit='auto', basic=False, sep='T')
--

Convert to the popular ISO format ``YYYY-MM-DDTHH:MM:SS``

The inverse of the ``parse_iso()`` method.
";
pub(crate) const PLAINDATETIME_PARSE: &CStr = c"\
parse(s, /, *, pattern=...)
--

Parse a plain datetime from a custom pattern string.

See :ref:`pattern-format` for details.

>>> PlainDateTime.parse(\"2024-03-15 14:30\", pattern=\"YYYY-MM-DD HH:mm\")
PlainDateTime(\"2024-03-15 14:30:00\")
";
pub(crate) const PLAINDATETIME_PARSE_ISO: &CStr = c"\
Parse the popular ISO format ``YYYY-MM-DDTHH:MM:SS``

The inverse of the ``format_iso()`` method.

>>> PlainDateTime.parse_iso(\"2020-08-15T23:12:00\")
PlainDateTime(\"2020-08-15 23:12:00\")
";
pub(crate) const PLAINDATETIME_REPLACE: &CStr = c"\
replace($self, /, *, year=..., month=..., day=..., hour=..., minute=..., second=..., nanosecond=...)
--

Create a new instance with the given fields replaced

A result that is not a valid date or time raises :class:`ValueError`.

>>> d = PlainDateTime(2021, 1, 31, 12, 30)
>>> d.replace(month=2, day=28)
PlainDateTime(\"2021-02-28 12:30:00\")
";
pub(crate) const PLAINDATETIME_REPLACE_DATE: &CStr = c"\
Create a new instance with the date replaced

>>> d = PlainDateTime(2021, 1, 2, 12, 30)
>>> d.replace_date(Date(2024, 2, 29))
PlainDateTime(\"2024-02-29 12:30:00\")
";
pub(crate) const PLAINDATETIME_REPLACE_TIME: &CStr = c"\
Create a new instance with the time replaced

>>> d = PlainDateTime(2021, 1, 2, 12, 30)
>>> d.replace_time(Time(8, 15, nanosecond=1))
PlainDateTime(\"2021-01-02 08:15:00.000000001\")
";
pub(crate) const PLAINDATETIME_ROUND: &CStr = c"\
round($self, unit='second', /, *, increment=1, mode='half_even')
--

Round the datetime to the specified unit and increment,
or to a multiple of a :class:`TimeDelta`.
Different rounding modes are available.

>>> d = PlainDateTime(2020, 8, 15, 23, 24, 18)
>>> d.round(\"day\")
PlainDateTime(\"2020-08-16 00:00:00\")
>>> d.round(\"minute\", increment=15, mode=\"floor\")
PlainDateTime(\"2020-08-15 23:15:00\")
";
pub(crate) const PLAINDATETIME_SINCE: &CStr = c"\
since($self, b, /, *, total=..., in_units=..., round_mode=..., round_increment=..., naive_arithmetic_ok=...)
--

Calculate the duration since another PlainDateTime,
in terms of the specified units.

>>> d1 = PlainDateTime(2020, 8, 15, 23, 12)
>>> d2 = PlainDateTime(2020, 8, 14, 22)
>>> d1.since(d2, in_units=[\"hours\", \"minutes\"],
...          round_increment=15,
...          round_mode=\"ceil\")
ItemizedDelta(\"PT25h15m\")
";
pub(crate) const PLAINDATETIME_START_OF: &CStr = c"\
The start of the given unit

>>> PlainDateTime(2024, 8, 15, 14, 30, 45).start_of(\"day\")
PlainDateTime(\"2024-08-15 00:00:00\")
>>> PlainDateTime(2024, 8, 15, 14, 30, 45).start_of(\"hour\")
PlainDateTime(\"2024-08-15 14:00:00\")
";
pub(crate) const PLAINDATETIME_SUBTRACT: &CStr = c"\
subtract($self, delta=..., /, *, years=0, months=0, weeks=0, days=0, hours=0, minutes=0, seconds=0, milliseconds=0, microseconds=0, nanoseconds=0, naive_arithmetic_ok=False)
--

Subtract a time amount from this datetime.

See :meth:`add` for more information.
";
pub(crate) const PLAINDATETIME_UNTIL: &CStr = c"\
until($self, b, /, *, total=..., in_units=..., round_mode=..., round_increment=..., naive_arithmetic_ok=...)
--

Inverse of the ``since()`` method. See :meth:`since` for more information.";
pub(crate) const TIME_FORMAT: &CStr = c"\
Format as a custom pattern string.

See :ref:`pattern-format` for details.

>>> Time(14, 30, 5).format(\"HH:mm:ss\")
'14:30:05'
>>> Time(14, 30).format(\"ii:mm aa\")
'02:30 PM'
";
pub(crate) const TIME_FORMAT_ISO: &CStr = c"\
format_iso($self, *, unit='auto', basic=False)
--

Format as the ISO 8601 time format.

Inverse of :meth:`parse_iso`.

>>> Time(12, 30, 0).format_iso(unit='millisecond')
'12:30:00.000'
>>> Time(4, 0, 59, nanosecond=40_000).format_iso(basic=True)
'040059.00004'
";
pub(crate) const TIME_HOUR: &CStr = c"\
The hour component of the time

>>> Time(12, 30, 0).hour
12
";
pub(crate) const TIME_MINUTE: &CStr = c"\
The minute component of the time

>>> Time(12, 30, 0).minute
30
";
pub(crate) const TIME_NANOSECOND: &CStr = c"\
The nanosecond component of the time

>>> Time(\"12:30:00.003\").nanosecond
3000000
";
pub(crate) const TIME_ON: &CStr = c"\
Combine a time with a date to create a datetime

>>> t = Time(12, 30)
>>> t.on(Date(2021, 1, 2))
PlainDateTime(\"2021-01-02 12:30:00\")

Then, use methods like :meth:`~PlainDateTime.assume_utc`
or :meth:`~PlainDateTime.assume_tz`
to find the corresponding exact time:

>>> t.on(Date(2021, 1, 2)).assume_tz(\"America/New_York\")
ZonedDateTime(\"2021-01-02 12:30:00-05:00[America/New_York]\")
";
pub(crate) const TIME_PARSE: &CStr = c"\
parse(s, /, *, pattern=...)
--

Parse a time from a custom pattern string.

See :ref:`pattern-format` for details.

>>> Time.parse(\"14:30:05\", pattern=\"HH:mm:ss\")
Time(\"14:30:05\")
>>> Time.parse(\"02:30 PM\", pattern=\"ii:mm aa\")
Time(\"14:30:00\")
";
pub(crate) const TIME_PARSE_ISO: &CStr = c"\
Create from the ISO 8601 time format

Inverse of :meth:`format_iso`

>>> Time.parse_iso(\"12:30:00\")
Time(\"12:30:00\")
";
pub(crate) const TIME_REPLACE: &CStr = c"\
replace($self, /, *, hour=..., minute=..., second=..., nanosecond=...)
--

Create a new instance with the given fields replaced

A result that is not a valid time raises :class:`ValueError`.

>>> t = Time(12, 30, 0)
>>> t.replace(minute=3, nanosecond=4_000)
Time(\"12:03:00.000004\")
";
pub(crate) const TIME_ROUND: &CStr = c"\
round($self, unit='second', /, *, increment=1, mode='half_even')
--

Round the time to the specified unit and increment,
or to a multiple of a :class:`TimeDelta`.
Various rounding modes are available.

>>> Time(12, 39, 59).round(\"minute\", increment=15)
Time(\"12:45:00\")
>>> Time(8, 9, 13).round(\"second\", increment=5, mode=\"floor\")
Time(\"08:09:10\")
>>> Time(12, 39, 59).round(TimeDelta(minutes=15))
Time(\"12:45:00\")

A :class:`Time` has no date to carry into, so rounding past the end of
the day wraps around to midnight:

>>> Time(23, 59, 59).round(\"minute\", mode=\"ceil\")
Time(\"00:00:00\")
";
pub(crate) const TIME_SECOND: &CStr = c"\
The second component of the time

>>> Time(12, 30, 0).second
0
";
pub(crate) const TIME_TO_STDLIB: &CStr = c"\
Convert to a standard library :class:`~datetime.time`

Note
----
Nanoseconds are truncated to microseconds.
If you need more control over rounding, use :meth:`round` first.
";
pub(crate) const TIMEDELTA_ADD: &CStr = c"\
add($self, delta=..., /, **kwargs)
--

Add time to this delta, returning a new delta.

Days and weeks are treated as exact 24-hour and 168-hour units,
which emits a :class:`~whenever.DaysAssumed24HoursWarning`.";
pub(crate) const TIMEDELTA_FORMAT_ISO: &CStr = c"\
Format as the *popular interpretation* of the ISO 8601 duration format.
May not strictly adhere to (all versions of) the standard.
See :ref:`here <iso8601-durations>` for more information.

Inverse of :meth:`parse_iso`.

>>> TimeDelta(hours=1, minutes=30).format_iso()
'PT1H30M'
";
pub(crate) const TIMEDELTA_IN_UNITS: &CStr = c"\
in_units($self, units, /, *, round_mode='trunc', round_increment=1, relative_to=..., days_assumed_24h_ok=...)
--

Convert to a :class:`ItemizedDelta` with the specified units

>>> d = TimeDelta(hours=2, minutes=30, seconds=23, milliseconds=500)
>>> d.in_units(['minutes', 'seconds'])
ItemizedDelta(\"PT150m24s\")
>>> (hrs, mins) = d.in_units(('hours', 'minutes'), round_mode='ceil').values()
(2, 31)

Parameters
----------
units
    A sequence of plural unit names, in descending order.
    Valid unit names are: ``weeks``, ``days``, ``hours``,
    ``minutes``, ``seconds``, ``nanoseconds``.
    ``years`` and ``months`` are also allowed if ``relative_to``
    is provided.
round_mode
    The rounding mode to use when rounding before conversion.
    See :meth:`round` for details.
round_increment
    The rounding increment to use when rounding before conversion.
    See :meth:`round` for details.
relative_to
    A reference datetime required when using calendar units
    (``years``, ``months``, ``days``, or ``weeks``) to account for variable unit lengths.

    - :class:`ZonedDateTime`: DST-aware; emits no warning
    - :class:`PlainDateTime`: does not account for time zones; emits
      :class:`NaiveArithmeticWarning`
    - :class:`OffsetDateTime`: does not account for DST changes; emits
      :class:`StaleOffsetWarning`

    The :class:`OffsetDateTime` case has no call-local escape: either
    convert the reference with :meth:`OffsetDateTime.assume_tz`
    first, or filter the :class:`StaleOffsetWarning` category.
";
pub(crate) const TIMEDELTA_PARSE_ISO: &CStr = c"\
Parse the *popular interpretation* of the ISO 8601 duration format.
Does not parse all possible ISO 8601 durations.
See :ref:`here <iso8601-durations>` for more information.

Inverse of :meth:`format_iso`

>>> TimeDelta.parse_iso(\"PT1H80M\")
TimeDelta(\"PT2h20m\")

Note
----
Any duration with a date part is considered invalid.
``PT0S`` is valid, but ``P0D`` is not.
";
pub(crate) const TIMEDELTA_ROUND: &CStr = c"\
round($self, unit='second', /, *, increment=1, mode='half_even', days_assumed_24h_ok=...)
--

Round the delta to the specified unit and increment,
or to a multiple of another :class:`TimeDelta`.
Various rounding modes are available.

>>> t = TimeDelta(seconds=12345)
TimeDelta(\"PT3h25m45s\")
>>> t.round(\"minute\")
TimeDelta(\"PT3h26m\")
>>> t.round(\"second\", increment=10, mode=\"floor\")
TimeDelta(\"PT3h25m40s\")
>>> t.round(TimeDelta(minutes=15))
TimeDelta(\"PT3h30m\")
";
pub(crate) const TIMEDELTA_SUBTRACT: &CStr = c"\
subtract($self, delta=..., /, **kwargs)
--

Subtract time from this delta, returning a new delta.

Days and weeks are treated as exact 24-hour and 168-hour units,
which emits a :class:`~whenever.DaysAssumed24HoursWarning`.";
pub(crate) const TIMEDELTA_TO_STDLIB: &CStr = c"\
Convert to a :class:`~datetime.timedelta`

>>> d = TimeDelta(hours=1, minutes=30)
>>> d.to_stdlib()
timedelta(seconds=5400)

Note
----
Nanoseconds are truncated to microseconds.
If you need more control over rounding, use :meth:`round` first.
";
pub(crate) const TIMEDELTA_TOTAL: &CStr = c"\
total($self, unit, /, *, relative_to=..., days_assumed_24h_ok=...)
--

The total size in the given unit, as a float (or int for nanoseconds)

For calendar units (years, months, weeks, days), a ``relative_to``
argument is required to determine the actual duration of each unit:

- :class:`ZonedDateTime`: DST-aware; emits no warning
- :class:`PlainDateTime`: no time zone context; emits
  :class:`NaiveArithmeticWarning`
- :class:`OffsetDateTime`: fixed offset; emits
  :class:`StaleOffsetWarning`

The :class:`OffsetDateTime` case has no call-local escape: either
convert the reference with :meth:`OffsetDateTime.assume_tz` first, or
filter the :class:`StaleOffsetWarning` category.

>>> d = TimeDelta(hours=1, minutes=30)
>>> d.total('minutes')
90.0
";
pub(crate) const ZONEDDATETIME_ADD: &CStr = c"\
add($self, delta=..., /, *, years=0, months=0, weeks=0, days=0, hours=0, minutes=0, seconds=0, milliseconds=0, microseconds=0, nanoseconds=0, disambiguation=...)
--

Return a new ``ZonedDateTime`` shifted by the given time amounts

Important
---------
Shifting by **calendar units** (e.g. months, weeks)
may result in an ambiguous time (e.g. during a DST transition).
Therefore, when adding calendar units, it's recommended to
specify how to handle such a situation using the ``disambiguation`` argument.

See `the documentation <https://whenever.rtfd.io/en/latest/guide/arithmetic.html>`__
for more information.
";
pub(crate) const ZONEDDATETIME_DAY_LENGTH: &CStr = c"\
The duration between the start of the current day and the next.
This is usually 24 hours, but may be different due to time zone transitions.

>>> ZonedDateTime(2020, 8, 15, tz=\"Europe/London\").day_length()
TimeDelta(\"PT24h\")
>>> ZonedDateTime(2023, 10, 29, tz=\"Europe/Amsterdam\").day_length()
TimeDelta(\"PT25h\")
";
pub(crate) const ZONEDDATETIME_DST_OFFSET: &CStr = c"\
The DST offset (adjustment) of the datetime

>>> ZonedDateTime(2020, 8, 15, tz=\"Europe/London\").dst_offset()
TimeDelta(\"PT1h\")
>>> ZonedDateTime(2020, 1, 15, tz=\"Europe/London\").dst_offset()
TimeDelta(\"PT0s\")

This value is ``TimeDelta.ZERO`` when DST is not active:

>>> d = ZonedDateTime(2020, 8, 15, tz=\"Europe/London\")
>>> if d.dst_offset():
...     print(\"DST is active\")
DST is active

Note
----
Some time zones have unusual DST rules. For example,
Europe/Dublin defines its standard time as IST (UTC+1) and uses
\"negative DST\" in winter. In such cases, this method
returns a negative value during winter.
";
pub(crate) const ZONEDDATETIME_END_OF: &CStr = c"\
The end of the given unit

>>> ZonedDateTime(2024, 8, 15, 14, 30, tz=\"America/New_York\").end_of(\"day\")
ZonedDateTime(\"2024-08-15 23:59:59.999999999-04:00[America/New_York]\")

See also :meth:`start_of`. A boundary skipped by a transition snaps to
the edge of the gap, so that successive intervals stay contiguous.
";
pub(crate) const ZONEDDATETIME_EXACT_EQ: &CStr = c"\
Deprecated alias for :meth:`strict_eq`.

.. deprecated:: 0.11
   Use :meth:`strict_eq` instead.
";
pub(crate) const ZONEDDATETIME_FORMAT: &CStr = c"\
Format as a custom pattern string.

See :ref:`pattern-format` for details.

>>> ZonedDateTime(2024, 3, 15, 14, 30, tz=\"Europe/Paris\").format(
...     \"YYYY-MM-DD HH:mmxxx'['VV']'\"
... )
'2024-03-15 14:30+01:00[Europe/Paris]'
";
pub(crate) const ZONEDDATETIME_FORMAT_ISO: &CStr = c"\
format_iso($self, *, unit='auto', basic=False, sep='T', tz_id_display=...)
--

Convert to the popular ISO format ``YYYY-MM-DDTHH:MM:SS±HH:MM[TZ_ID]``.

The inverse of the ``parse_iso()`` method.

>>> zdt = ZonedDateTime(2020, 8, 15, hour=23, minute=12, tz=\"Europe/London\")
>>> zdt.format_iso(unit=\"minute\", basic=True)
\"20200815T2312+0100[Europe/London]\"

Parameters
----------
unit
    The smallest unit to include in the output.
    ``\"auto\"`` is the same as ``\"nanosecond\"``,
    except that trailing zeroes are omitted from the time part.
basic
    Whether to use the basic ISO format (without separators) instead of the extended one.
sep
    The separator between the date and time parts.
tz_id_display
    Whether to include the time zone ID in the output.
    ``\"required\"`` (default) raises :exc:`ValueError` when the time zone
    has no ID, which happens for some system time zones.
    ``\"if_available\"`` writes the ID when there is one and omits it otherwise.
    ``\"omit\"`` never writes it.

Important
---------
The time zone ID is a recent extension to the ISO 8601 format (RFC 9557).
Although it is gaining popularity, it is not yet widely supported
by ISO 8601 parsers.
";
pub(crate) const ZONEDDATETIME_FROM_SYSTEM_TZ: &CStr = c"\
from_system_tz(year, month, day, hour=0, minute=0, second=0, *, nanosecond=0, disambiguation=...)
--

Create an instance in the system time zone.

.. deprecated:: 0.11
   Use ``ZonedDateTime(..., tz=SYSTEM_TZ)`` instead.

Equivalent to ``ZonedDateTime(..., tz=SYSTEM_TZ)``.

>>> ZonedDateTime.from_system_tz(2020, 8, 15, hour=23, minute=12)
ZonedDateTime(\"2020-08-15 23:12:00+02:00[Europe/Berlin]\")
";
pub(crate) const ZONEDDATETIME_FROM_TIMESTAMP: &CStr = c"\
from_timestamp(value, /, *, tz)
--

Create an instance from a UNIX timestamp (in seconds).

.. deprecated:: 0.11
   Create an :class:`Instant` and call ``to_tz()`` instead.

The inverse of the ``timestamp()`` method.
";
pub(crate) const ZONEDDATETIME_FROM_TIMESTAMP_MILLIS: &CStr = c"\
from_timestamp_millis(value, /, *, tz)
--

Create an instance from a UNIX timestamp (in milliseconds).

.. deprecated:: 0.11
   Use ``Instant.from_timestamp(..., unit=\"millisecond\").to_tz()``.

The inverse of the ``timestamp_millis()`` method.
";
pub(crate) const ZONEDDATETIME_FROM_TIMESTAMP_NANOS: &CStr = c"\
from_timestamp_nanos(value, /, *, tz)
--

Create an instance from a UNIX timestamp (in nanoseconds).

.. deprecated:: 0.11
   Use ``Instant.from_timestamp(..., unit=\"nanosecond\").to_tz()``.

The inverse of the ``timestamp_nanos()`` method.
";
pub(crate) const ZONEDDATETIME_IS_AMBIGUOUS: &CStr = c"\
Whether this local time occurs twice in its time zone.

.. deprecated:: 0.11
   Use :meth:`is_repeated` instead.
";
pub(crate) const ZONEDDATETIME_IS_REPEATED: &CStr = c"\
Whether this local time occurs twice in its time zone
(a :term:`repeated local time`), for example on the night
daylight saving time ends.

>>> ZonedDateTime(2020, 8, 15, 23, tz=\"Europe/London\").is_repeated()
False
>>> ZonedDateTime(2023, 10, 29, 2, 15, tz=\"Europe/Amsterdam\").is_repeated()
True
";
pub(crate) const ZONEDDATETIME_NEXT_TRANSITION: &CStr = c"\
The next time zone transition after this datetime, if any.

Returns ``None`` if the time zone has no further transitions
(e.g. for UTC or fixed-offset time zones).

>>> d = ZonedDateTime(2024, 1, 1, tz=\"America/New_York\")
>>> d.next_transition()
ZonedDateTime(\"2024-03-10 03:00:00-04:00[America/New_York]\")
";
pub(crate) const ZONEDDATETIME_NOW: &CStr = c"\
Create an instance from the current time in the given time zone.
Pass ``SYSTEM_TZ`` for the system time zone.

>>> ZonedDateTime.now(\"Europe/Amsterdam\")
ZonedDateTime(\"2024-03-09 23:00:00+01:00[Europe/Amsterdam]\")
";
pub(crate) const ZONEDDATETIME_NOW_IN_SYSTEM_TZ: &CStr = c"\
Create an instance from the current time in the system time zone.

.. deprecated:: 0.11
   Use ``ZonedDateTime.now(SYSTEM_TZ)`` instead.

Equivalent to ``now(SYSTEM_TZ)``.
";
pub(crate) const ZONEDDATETIME_PARSE: &CStr = c"\
parse(s, /, *, pattern=..., disambiguation=..., offset_mismatch='raise')
--

Parse a zoned datetime from a custom pattern string.

The pattern **must** include a time zone ID field (``VV``).
An offset field (``x``/``X``) is optional but recommended for
disambiguation during DST transitions.
See the `timezone-resolution guide
<https://whenever.readthedocs.io/en/latest/guide/resolving-local-times.html#offset-mismatch>`_
for how ``offset_mismatch`` interacts with ``disambiguation``.
See :ref:`pattern-format` for details.

.. tip::

    If your input string doesn't include a time zone ID, parse it with
    :meth:`PlainDateTime.parse` first, then convert using
    :meth:`~PlainDateTime.assume_tz`.

>>> ZonedDateTime.parse(
...     \"2024-03-15 14:30+01:00[Europe/Paris]\",
...     pattern=\"YYYY-MM-DD HH:mmxxx'['VV']'\",
... )
ZonedDateTime(\"2024-03-15 14:30:00+01:00[Europe/Paris]\")
";
pub(crate) const ZONEDDATETIME_PARSE_ISO: &CStr = c"\
parse_iso(s, /, *, disambiguation=..., offset_mismatch='raise')
--

Parse from the popular ISO format ``YYYY-MM-DDTHH:MM:SS±HH:MM[TZ_ID]``

The inverse of the ``format_iso()`` method.

See the `timezone-resolution guide
<https://whenever.readthedocs.io/en/latest/guide/resolving-local-times.html#offset-mismatch>`_
for how ``offset_mismatch`` interacts with ``disambiguation``.

>>> ZonedDateTime.parse_iso(\"2020-08-15T23:12:00+01:00[Europe/London]\")
ZonedDateTime(\"2020-08-15 23:12:00+01:00[Europe/London]\")

Important
---------
The time zone ID is a recent extension to the ISO 8601 format (RFC 9557).
Although it is gaining popularity, it is not yet widely supported.
";
pub(crate) const ZONEDDATETIME_PREV_TRANSITION: &CStr = c"\
The previous time zone transition before this datetime, if any.

Returns ``None`` if the time zone has no earlier transitions
(e.g. for UTC or fixed-offset time zones).

>>> d = ZonedDateTime(2024, 1, 1, tz=\"America/New_York\")
>>> d.prev_transition()
ZonedDateTime(\"2023-11-05 01:00:00-05:00[America/New_York]\")
";
pub(crate) const ZONEDDATETIME_REPLACE: &CStr = c"\
replace($self, /, *, year=..., month=..., day=..., hour=..., minute=..., second=..., nanosecond=..., tz=..., disambiguation=...)
--

Create a new instance with the given fields replaced

Tip
---
If you need the start or end of a unit (e.g. the start of the day),
use :meth:`start_of` and :meth:`end_of` instead.

Important
---------
Replacing fields keeps the current offset while it is valid for the
new local time (**offset-preserving resolution**), so a repeated
local time stays on its side of the transition. A skipped local
time, a changed ``tz=``, or an offset that no longer applies falls
to ``disambiguation=``, which is ``\"compatible\"`` with
:class:`ImplicitDisambiguationWarning` when omitted. A stated ``tz=``
keeps the local fields and moves the instant; :meth:`to_tz` keeps
the instant. See :ref:`offset-preserving`.

>>> d = ZonedDateTime(2023, 10, 29, 2, 30, tz=\"Europe/Paris\", disambiguation=\"later\")
>>> d.replace(minute=45)  # still the second occurrence
ZonedDateTime(\"2023-10-29 02:45:00+01:00[Europe/Paris]\")
>>> d.replace(minute=45, disambiguation=\"earlier\")
ZonedDateTime(\"2023-10-29 02:45:00+02:00[Europe/Paris]\")
";
pub(crate) const ZONEDDATETIME_REPLACE_DATE: &CStr = c"\
replace_date($self, date, /, *, disambiguation=...)
--

Create a new instance with the date replaced

See :meth:`replace`: the current offset is kept while it applies to
the new local time; otherwise ``disambiguation=`` decides, with
:class:`ImplicitDisambiguationWarning` when omitted.

>>> d = ZonedDateTime(2023, 10, 29, 2, 30, tz=\"Europe/Paris\", disambiguation=\"later\")
>>> d.replace_date(Date(2023, 10, 30))
ZonedDateTime(\"2023-10-30 02:30:00+01:00[Europe/Paris]\")
";
pub(crate) const ZONEDDATETIME_REPLACE_TIME: &CStr = c"\
replace_time($self, time, /, *, disambiguation=...)
--

Create a new instance with the time replaced

See :meth:`replace`: the current offset is kept while it applies to
the new local time; otherwise ``disambiguation=`` decides, with
:class:`ImplicitDisambiguationWarning` when omitted.

>>> d = ZonedDateTime(2023, 10, 29, 2, 30, tz=\"Europe/Paris\", disambiguation=\"later\")
>>> d.replace_time(Time(12))
ZonedDateTime(\"2023-10-29 12:00:00+01:00[Europe/Paris]\")
";
pub(crate) const ZONEDDATETIME_ROUND: &CStr = c"\
round($self, unit='second', /, *, increment=1, mode='half_even')
--

Round the datetime to the specified unit and increment,
or to a multiple of a :class:`TimeDelta`.
Different rounding modes are available.

>>> d = ZonedDateTime(\"2020-08-15 23:24:18+02:00[Europe/Paris]\")
>>> d.round(\"day\")
ZonedDateTime(\"2020-08-16 00:00:00+02:00[Europe/Paris]\")
>>> d.round(\"minute\", increment=15, mode=\"floor\")
ZonedDateTime(\"2020-08-15 23:15:00+02:00[Europe/Paris]\")

Notes
-----
* A rounded time that is repeated keeps the current offset if that
  offset is still valid, and takes the earlier one otherwise.
  A rounded time that is skipped becomes the first instant after
  the gap.
* Rounding to a day compares the time elapsed since the start of the
  day with the day's length. On the 23-hour day of 2023-03-26 in
  Amsterdam, 11:31 therefore rounds down and 12:31 rounds up.
";
pub(crate) const ZONEDDATETIME_SINCE: &CStr = c"\
since($self, b, /, *, total=..., in_units=..., round_mode=..., round_increment=...)
--

Calculate the duration since another ZonedDateTime,
in terms of the specified units.

>>> d1 = ZonedDateTime(\"2020-08-15T23:12:00+01:00[Europe/London]\")
>>> d2 = ZonedDateTime(\"2020-08-14T22:00:00+09:00[Asia/Tokyo]\")
>>> d1.since(d2, in_units=[\"hours\", \"minutes\"],
...          round_increment=15,
...          round_mode=\"ceil\")
ItemizedDelta(\"PT33h15m\")

When calculating calendar units (years, months, weeks, days),
both datetimes must have the same time zone.
";
pub(crate) const ZONEDDATETIME_START_OF: &CStr = c"\
The start of the given unit

>>> ZonedDateTime(2024, 8, 15, 14, 30, tz=\"America/New_York\").start_of(\"day\")
ZonedDateTime(\"2024-08-15 00:00:00-04:00[America/New_York]\")
>>> ZonedDateTime(2024, 8, 15, 14, 30, tz=\"America/New_York\").start_of(\"hour\")
ZonedDateTime(\"2024-08-15 14:00:00-04:00[America/New_York]\")

A boundary skipped by a transition snaps to the edge of the gap, so
that successive intervals stay contiguous.

For ``\"hour\"``, ``\"minute\"``, and ``\"second\"``, a repeated boundary
keeps the current offset if that offset is still valid. For
``\"day\"``, ``\"week_mon\"``, ``\"week_sun\"``, ``\"month\"``, and
``\"year\"``, a repeated boundary always takes the earlier occurrence,
so that every value on the same date shares one boundary.
";
pub(crate) const ZONEDDATETIME_STRICT_EQ: &CStr = c"\
Compare two values, including what ``==`` ignores.

``ZonedDateTime.__eq__`` ignores the argument's type, the local
datetime, the offset, and the time zone. A time zone is compared by
identifier and definition; the system time zone has no identifier and
so compares by definition alone. An argument of a different type
raises :exc:`TypeError`.

>>> a = ZonedDateTime(2020, 8, 15, hour=12, tz=\"Europe/Amsterdam\")
>>> b = a.to_tz(\"America/New_York\")
>>> a == b
True  # same moment in time
>>> a.strict_eq(b)
False  # different local datetime, offset and time zone

See :ref:`strict-equality` for the rules on every type.
";
pub(crate) const ZONEDDATETIME_SUBTRACT: &CStr = c"\
subtract($self, delta=..., /, *, years=0, months=0, weeks=0, days=0, hours=0, minutes=0, seconds=0, milliseconds=0, microseconds=0, nanoseconds=0, disambiguation=...)
--

The inverse of the ``add()`` method. See :meth:`add` for more information.";
pub(crate) const ZONEDDATETIME_TZ: &CStr = c"\
Deprecated alias of :attr:`tz_id`.

.. deprecated:: 0.11
   Use :attr:`tz_id` instead.
";
pub(crate) const ZONEDDATETIME_TZ_ABBREV: &CStr = c"\
The time zone abbreviation (e.g. ``\"EST\"``, ``\"CEST\"``).

>>> ZonedDateTime(2020, 8, 15, tz=\"Europe/London\").tz_abbrev()
'BST'
>>> ZonedDateTime(2020, 1, 15, tz=\"Europe/London\").tz_abbrev()
'GMT'

Warning
-------
The abbreviation is often ambiguous and may not be unique,
but it is commonly used in human-readable formats.
Use the time zone ID (e.g. ``\"Europe/London\"``) for unambiguous identification of time zones.
";
pub(crate) const ZONEDDATETIME_TZ_ID: &CStr = c"\
The time zone ID. In rare cases, this may be ``None``,
if the ``ZonedDateTime`` was created from a :ref:`system time zone
<systemtime>` without a time zone ID.
";
pub(crate) const ZONEDDATETIME_UNTIL: &CStr = c"\
until($self, b, /, *, total=..., in_units=..., round_mode=..., round_increment=...)
--

Inverse of the ``since()`` method. See :meth:`since` for more information.";
pub(crate) const BASICCONVERSIONS_TO_STDLIB: &CStr = c"\
Convert to a standard library :class:`~datetime.datetime`

Note
----
- Nanoseconds are truncated to microseconds.
  If you wish to customize the rounding behavior, use
  the ``round()`` method first.
- For :class:`ZonedDateTime` linked to a system time zone without a
  IANA time zone ID, the returned Python datetime will have
  a fixed offset (:class:`~datetime.timezone` tzinfo)
";
pub(crate) const EXACTANDLOCALTIME_OFFSET: &CStr = c"\
The UTC offset of the datetime";
pub(crate) const EXACTANDLOCALTIME_TO_INSTANT: &CStr = c"\
Get the underlying instant in time

>>> d = ZonedDateTime(2020, 8, 15, hour=23, tz=\"Europe/Amsterdam\")
>>> d.to_instant()
Instant(\"2020-08-15 21:00:00Z\")
";
pub(crate) const EXACTANDLOCALTIME_TO_PLAIN: &CStr = c"\
Get the underlying date and time without offset or time zone

As an inverse, :class:`PlainDateTime` has methods
:meth:`~PlainDateTime.assume_utc`, :meth:`~PlainDateTime.assume_fixed_offset`,
and :meth:`~PlainDateTime.assume_tz`.
";
pub(crate) const EXACTTIME_DIFFERENCE: &CStr = c"\
Calculate the exact time difference between two datetimes.

This method returns the exact elapsed :class:`TimeDelta` between
two instants in time. Equivalent to the subtraction operator (``-``).

Use :meth:`~whenever.ZonedDateTime.since` or
:meth:`~whenever.ZonedDateTime.until` for more advanced
options such as calendar units, unit decomposition, and rounding.
";
pub(crate) const EXACTTIME_EXACT_EQ: &CStr = c"\
Deprecated alias for :meth:`strict_eq`.

.. deprecated:: 0.11
   Use :meth:`strict_eq` instead.
";
pub(crate) const EXACTTIME_STRICT_EQ: &CStr = c"\
Compare two values, including what ``==`` ignores.

``Instant.__eq__`` ignores nothing but the argument's type, while
``OffsetDateTime.__eq__`` also ignores the local datetime and the
offset. An argument of a different type raises :exc:`TypeError`.

>>> a = OffsetDateTime(2020, 8, 15, hour=12, offset=hours(1))
>>> b = OffsetDateTime(2020, 8, 15, hour=13, offset=hours(2))
>>> a == b
True  # equivalent instants
>>> a.strict_eq(b)
False  # different local datetime and offset
>>> a.strict_eq(Instant.now())
TypeError  # different types

See :ref:`strict-equality` for the rules on every type.
";
pub(crate) const EXACTTIME_TIMESTAMP: &CStr = c"\
timestamp($self, *, unit='second')
--

The UNIX timestamp in the requested unit. Inverse of :meth:`from_timestamp`.

>>> Instant.from_utc(1970, 1, 1).timestamp()
0
>>> ts = 1_123_000_000
>>> Instant.from_timestamp(ts).timestamp() == ts
True

Note
----
In contrast to the standard library, this method always returns an integer,
not a float. This is because floating point timestamps are not precise
enough to represent all instants to nanosecond precision.
This decision is consistent with other modern date-time libraries.

Values before the epoch are floored at the requested unit. For example,
``1969-12-31T23:59:59.999999999Z`` has timestamp ``-1`` in seconds,
milliseconds, microseconds, and nanoseconds. This differs from applying
``int()`` to a negative float, which truncates toward zero.
";
pub(crate) const EXACTTIME_TIMESTAMP_MILLIS: &CStr = c"\
Like :meth:`timestamp`, but with millisecond precision.

.. deprecated:: 0.11
   Use ``timestamp(unit=\"millisecond\")`` instead.
";
pub(crate) const EXACTTIME_TIMESTAMP_NANOS: &CStr = c"\
Like :meth:`timestamp`, but with nanosecond precision.

.. deprecated:: 0.11
   Use ``timestamp(unit=\"nanosecond\")`` instead.
";
pub(crate) const EXACTTIME_TO_FIXED_OFFSET: &CStr = c"\
to_fixed_offset($self, offset=..., /)
--

Convert to an OffsetDateTime that represents the same moment in time.

If no offset is given, the offset is taken from the original datetime.
";
pub(crate) const EXACTTIME_TO_SYSTEM_TZ: &CStr = c"\
Convert to a ZonedDateTime of the system's time zone.

.. deprecated:: 0.11
   Use ``to_tz(SYSTEM_TZ)`` instead.
";
pub(crate) const EXACTTIME_TO_TZ: &CStr = c"\
Convert to a ZonedDateTime that represents the same moment in time.

Raises
------
~whenever.TimeZoneNotFoundError
    If the time zone ID is not found in the time zone database.
";
pub(crate) const LOCALTIME_DATE: &CStr = c"\
The date part of the datetime

>>> d = PlainDateTime(\"2020-01-02 03:04:05\")
>>> date = d.date()
>>> date
Date(\"2020-01-02\")

To perform the inverse, use :meth:`Date.at` and a method
like :meth:`~PlainDateTime.assume_utc` or
:meth:`~PlainDateTime.assume_tz`:

>>> date.at(d.time()).assume_tz(\"Europe/London\")
ZonedDateTime(\"2020-01-02 03:04:05+00:00[Europe/London]\")
";
pub(crate) const LOCALTIME_DAY: &CStr = c"\
The day component of the datetime";
pub(crate) const LOCALTIME_DAY_OF_WEEK: &CStr = c"\
The day of the week

>>> PlainDateTime(2021, 1, 2, 12).day_of_week()
Weekday.SATURDAY
";
pub(crate) const LOCALTIME_DAY_OF_YEAR: &CStr = c"\
Ordinal day in the year (1--366)

>>> PlainDateTime(2021, 1, 2).day_of_year()
2
";
pub(crate) const LOCALTIME_DAYS_IN_MONTH: &CStr = c"\
Number of days in the current month (28--31)

>>> PlainDateTime(2024, 2, 1).days_in_month()
29
";
pub(crate) const LOCALTIME_DAYS_IN_YEAR: &CStr = c"\
Number of days in the current year (365 or 366)

>>> PlainDateTime(2024, 1, 1).days_in_year()
366
";
pub(crate) const LOCALTIME_HOUR: &CStr = c"\
The hour component of the datetime";
pub(crate) const LOCALTIME_IN_LEAP_YEAR: &CStr = c"\
Whether the year of this datetime is a leap year

>>> PlainDateTime(2024, 1, 1).in_leap_year()
True
";
pub(crate) const LOCALTIME_MINUTE: &CStr = c"\
The minute component of the datetime";
pub(crate) const LOCALTIME_MONTH: &CStr = c"\
The month component of the datetime";
pub(crate) const LOCALTIME_NANOSECOND: &CStr = c"\
The nanosecond component of the datetime";
pub(crate) const LOCALTIME_SECOND: &CStr = c"\
The second component of the datetime";
pub(crate) const LOCALTIME_TIME: &CStr = c"\
The time-of-day part of the datetime

>>> d = ZonedDateTime(\"2021-01-02T03:04:05+01:00[Europe/Paris]\")
>>> time = d.time()
>>> time
Time(\"03:04:05\")

To perform the inverse, use :meth:`Time.on` and a method
like :meth:`~PlainDateTime.assume_utc` or
:meth:`~PlainDateTime.assume_tz`:

>>> time.on(d.date()).assume_tz(\"Europe/Paris\")
ZonedDateTime(\"2021-01-02 03:04:05+01:00[Europe/Paris]\")
";
pub(crate) const LOCALTIME_YEAR: &CStr = c"\
The year component of the datetime";
pub(crate) const CANNOT_ROUND_DAY_MSG: &CStr = c"Cannot round to day, because days do not have a fixed length. Due to daylight saving time, some days have 23 or 25 hours. If you wish to round to exactly 24 hours, use `round('hour', increment=24)`.";
pub(crate) const DAYS_NOT_ALWAYS_24H_MSG: &CStr = c"You are using days or weeks as exact time, so Whenever will treat each day as exactly 24 hours. A calendar day can be 23 or 25 hours during a DST transition, so this may differ from calendar arithmetic. If you mean calendar days, perform the operation on a ZonedDateTime or pass `relative_to=...` where supported. If fixed 24-hour periods are intentional, pass `days_assumed_24h_ok=True`. For project-wide warning configuration, see https://whenever.readthedocs.io/en/latest/guide/warnings.html";
pub(crate) const FORMAT_ISO_NO_TZ_MSG: &CStr = c"This ZonedDateTime has no time zone ID and cannot be formatted in the standard ISO format, which requires it. This typically means the ZonedDateTime was created from a system time zone with an unknown ID. To format without the time zone designator, set the `tz_id_display=` argument to 'never' or 'auto'.";
pub(crate) const IMPLICIT_DISAMBIGUATION_MSG: &CStr = c"resolving a local datetime that is repeated or skipped by a time zone transition without an explicit disambiguation policy can silently select the wrong instant; pass disambiguation='compatible', 'earlier', 'later', or 'raise'. See https://whenever.readthedocs.io/en/latest/guide/resolving-local-times.html";
pub(crate) const INCREMENT_MSG: &CStr = c"invalid increment: must be positive and divide a 24-hour day evenly";
pub(crate) const INTEGER_OFFSET_DEPRECATION_MSG: &CStr = c"integer offsets are deprecated because their unit is implicit; pass a TimeDelta instead, for example hours(2)";
pub(crate) const OFFSET_DATETIME_DOCS_MSG: &CStr = c"For comprehensive OffsetDateTime guidance, see https://whenever.readthedocs.io/en/latest/guide/choosing-a-type.html#offset-datetime-guidance for details and examples.";
pub(crate) const OFFSET_FROM_TIMESTAMP_STALE_MSG: &CStr = c"You are converting a timestamp using a fixed UTC offset. The result is correct for that offset, but the offset may be stale relative to the region you intend at this timestamp. If you mean a named time zone, use ZonedDateTime.from_timestamp(ts, tz='<tz>'); if you only need the instant, use Instant.from_timestamp(ts). If the fixed offset is intentional, pass `stale_offset_ok=True`. For comprehensive OffsetDateTime guidance, see https://whenever.readthedocs.io/en/latest/guide/choosing-a-type.html#offset-datetime-guidance for details and examples. For project-wide warning configuration, see https://whenever.readthedocs.io/en/latest/guide/warnings.html";
pub(crate) const OFFSET_NOW_STALE_MSG: &CStr = c"You are getting the current time using a fixed UTC offset. A fixed offset has no time zone rules, so it may be stale relative to the region you intend after a DST or other rule change. If you mean a named time zone, use ZonedDateTime.now('<tz>'); if you only need the current instant, use Instant.now(). If the fixed offset is intentional, pass `stale_offset_ok=True`. For comprehensive OffsetDateTime guidance, see https://whenever.readthedocs.io/en/latest/guide/choosing-a-type.html#offset-datetime-guidance for details and examples. For project-wide warning configuration, see https://whenever.readthedocs.io/en/latest/guide/warnings.html";
pub(crate) const OFFSET_REPLACE_STALE_MSG: &CStr = c"Replacing fields of an OffsetDateTime is valid and preserves its observed UTC offset. That offset may be stale relative to the source time zone if the result is in a different DST or time zone rule period (e.g. after replacing the month on a datetime in a European time zone). Convert to ZonedDateTime first (using .assume_tz()) for field replacement that accounts for the time zone. If the fixed offset is intentional, pass `stale_offset_ok=True`. For comprehensive OffsetDateTime guidance, see https://whenever.readthedocs.io/en/latest/guide/choosing-a-type.html#offset-datetime-guidance for details and examples. For project-wide warning configuration, see https://whenever.readthedocs.io/en/latest/guide/warnings.html";
pub(crate) const OFFSET_ROUND_STALE_MSG: &CStr = c"Rounding an OffsetDateTime is valid and preserves its observed UTC offset. That offset may be stale relative to the source time zone if the rounded time crosses a DST or other time zone boundary. Convert to a ZonedDateTime first (using .assume_tz()) for rounding that accounts for the time zone. If the fixed offset is intentional, pass `stale_offset_ok=True`. For comprehensive OffsetDateTime guidance, see https://whenever.readthedocs.io/en/latest/guide/choosing-a-type.html#offset-datetime-guidance for details and examples. For project-wide warning configuration, see https://whenever.readthedocs.io/en/latest/guide/warnings.html";
pub(crate) const OFFSET_SHIFT_STALE_MSG: &CStr = c"An OffsetDateTime's offset is usually an observation, not a time zone rule. The arithmetic is mathematically valid and preserves that fixed offset, but OffsetDateTime does not retain regional time zone rules. The result's offset may therefore be stale relative to the source time zone, even after an exact shift. If the originating time zone is known, convert to ZonedDateTime first using .assume_tz(). If fixed-offset arithmetic is intentional or the risk is accepted, pass `stale_offset_ok=True`. For an entirely fixed-offset domain, configure StaleOffsetWarning globally. For comprehensive OffsetDateTime guidance, see https://whenever.readthedocs.io/en/latest/guide/choosing-a-type.html#offset-datetime-guidance for details and examples. For project-wide warning configuration, see https://whenever.readthedocs.io/en/latest/guide/warnings.html";
pub(crate) const OFFSET_START_END_OF_STALE_MSG: &CStr = c"Getting the start or end of a unit on an OffsetDateTime is valid and preserves its observed UTC offset. That offset may be stale relative to the source time zone at the resulting time (e.g. the start of the year may have a different UTC offset due to DST). Convert to ZonedDateTime first (using .assume_tz()) for results that account for the time zone. If the fixed offset is intentional, pass `stale_offset_ok=True`. For comprehensive OffsetDateTime guidance, see https://whenever.readthedocs.io/en/latest/guide/choosing-a-type.html#offset-datetime-guidance for details and examples. For project-wide warning configuration, see https://whenever.readthedocs.io/en/latest/guide/warnings.html";
pub(crate) const PLAIN_DIFF_UNAWARE_MSG: &CStr = c"Calculating the difference between two PlainDateTime values does not account for time zone transitions that may have occurred between them: for example, PlainDateTime(2023, 3, 26, 3, 0) - PlainDateTime(2023, 3, 26, 1, 0) gives 2h, but in Amsterdam clocks jumped from 2:00 to 3:00 that morning, so only 1 real hour elapsed. Use .assume_tz('<tz>') for both values if you know the time zone. If time zone transitions are intentionally irrelevant here, pass `naive_arithmetic_ok=True`. For project-wide warning configuration, see https://whenever.readthedocs.io/en/latest/guide/warnings.html";
pub(crate) const PLAIN_RELATIVE_TO_UNAWARE_MSG: &CStr = c"Using a PlainDateTime as reference does not account for time zone transitions: without a time zone, converting between calendar units (months, days) and exact time units (hours, seconds) is ambiguous across DST boundaries. Use .assume_tz('<tz>') for results that account for the time zone. If time zone transitions are intentionally irrelevant here, pass `naive_arithmetic_ok=True`. For project-wide warning configuration, see https://whenever.readthedocs.io/en/latest/guide/warnings.html";
pub(crate) const PLAIN_SHIFT_UNAWARE_MSG: &CStr = c"Shifting a PlainDateTime by exact time units does not account for time zone transitions that may occur in the interval (e.g. adding 2 hours to 2023-03-26 01:30 in Amsterdam crosses the spring-forward transition, so only 1 real hour has passed). Use .assume_tz('<tz>') + delta if you know the time zone. If time zone transitions are intentionally irrelevant here, pass `naive_arithmetic_ok=True`. For project-wide warning configuration, see https://whenever.readthedocs.io/en/latest/guide/warnings.html";
pub(crate) const RANGE_MSG: &CStr = c"value or calculation out of range";
pub(crate) const STALE_OFFSET_CALENDAR_MSG: &CStr = c"You are calculating calendar units relative to an OffsetDateTime. Because it contains only a fixed offset, Whenever must assume that the offset remains constant throughout the calculation. That offset may be stale relative to the source time zone during part of the period if the value represents a region that crosses a DST or other rule change. Use a ZonedDateTime for calendar arithmetic that accounts for the time zone. If the fixed-offset assumption is intentional, pass `stale_offset_ok=True`. For comprehensive OffsetDateTime guidance, see https://whenever.readthedocs.io/en/latest/guide/choosing-a-type.html#offset-datetime-guidance for details and examples. For project-wide warning configuration, see https://whenever.readthedocs.io/en/latest/guide/warnings.html";
pub(crate) const WARNING_HANDLING_DOCS_MSG: &CStr = c"For project-wide warning configuration, see https://whenever.readthedocs.io/en/latest/guide/warnings.html";
pub(crate) const ZONEINFO_NO_KEY_MSG: &CStr = c"Can't determine the IANA time zone ID of the given datetime: The 'key' attribute of the datetime's ZoneInfo object is None. 
This typically means the ZoneInfo object represents the system time zone with an unknown ID. As an alternative, you can construct an OffsetDateTime from the standard-library datetime, but be aware this is a lossy conversion that only preserves the current UTC offset and discards future daylight saving rules. Please note that a time zone abbreviation like 'CEST' from datetime.tzname() is not a valid IANA time zone ID and cannot be used here.";
